/**
 * GET
 */
export const GET_OFFLINE_STATUS = "GET_OFFLINE_STATUS";
export const GET_OFFLINE_LOADING_STATUS = "GET_OFFLINE_LOADING_STATUS";
export const GET_CURRENT_OFFLINE_LOADING = "GET_CURRENT_OFFLINE_LOADING";

/**
 * SET
 */
export const SET_OFFLINE_STATUS = "SET_OFFLINE_STATUS";
export const SET_OFFLINE_LOADING_STATUS = "SET_OFFLINE_LOADING_STATUS";
export const SET_CURRENT_OFFLINE_LOADING = "SET_CURRENT_OFFLINE_LOADING";

/**
 * ACTIONS
 */
export const PUSH_TO_SERVER = "PUSH_TO_SERVER";
export const RESET_CURRENT_OFFLINE_LOADING = "RESET_CURRENT_OFFLINE_LOADING";
export const SET_OFFLINE_SELECTED_ORGUNITS = "SET_OFFLINE_SELECTED_ORGUNITS";
