/**
 * GET
 */
export const GET_OFFLINE_STATUS = "GET_OFFLINE_STATUS";
export const GET_OFFLINE_LOADING_STATUS = "GET_OFFLINE_LOADING_STATUS";

/**
 * SET
 */
export const SET_OFFLINE_STATUS = "SET_OFFLINE_STATUS";
export const SET_OFFLINE_LOADING_STATUS = "SET_OFFLINE_STATUS";

/**
 * ACTIONS
 */
export const PUSH_TO_SERVER = "PUSH_TO_SERVER";
