const originMetadata = [
  {
    name: "Family member details 4.0 ID type",
    created: "2024-11-20T13:43:38.194",
    lastUpdated: "2024-11-20T14:42:36.510",
    translations: [],
    program: {
      id: "xvzrp56zKvI",
    },
    displayInList: true,
    sortOrder: 1,
    mandatory: false,
    renderOptionsAsRadio: false,
    searchable: false,
    valueType: "TEXT",
    displayShortName: "Family member details 4.0 ID type",
    displayName: "Family member details 4.0 ID type",
    favorite: false,
    id: "dZ2Z2FrRPDe",
    attributeValues: [],
    trackedEntityAttribute: {
      formName: "ID type",
      valueType: "TEXT",
      unique: false,
      pattern: "",
      displayName: "ID type",
      displayShortName: "ID type",
      displayFormName: "ID type",
      optionSetValue: false,
      id: "CADfVSQEVVi",
      attributeValues: [],
    },
  },
  {
    name: "Family member details 4.0 Country ID",
    created: "2024-11-20T13:43:38.194",
    lastUpdated: "2024-11-20T14:42:36.511",
    translations: [],
    externalAccess: false,
    userGroupAccesses: [],
    userAccesses: [],
    favorites: [],
    program: {
      id: "xvzrp56zKvI",
    },
    displayInList: true,
    sortOrder: 2,
    mandatory: false,
    renderOptionsAsRadio: false,
    searchable: false,
    valueType: "TEXT",
    displayShortName: "Family member details 4.0 Country ID",
    displayName: "Family member details 4.0 Country ID",
    favorite: false,
    id: "KONEkGFTb2s",
    attributeValues: [],
    trackedEntityAttribute: {
      formName: "Country ID",
      valueType: "TEXT",
      unique: false,
      pattern: "",
      displayName: "Country ID",
      displayShortName: "Country ID",
      displayFormName: "Country ID",
      optionSetValue: false,
      id: "rOA2ACbkXug",
      attributeValues: [],
    },
  },
  {
    name: "Family member details 4.0 UHID",
    created: "2024-11-20T13:43:38.194",
    lastUpdated: "2024-11-20T14:42:36.511",
    translations: [],
    externalAccess: false,
    userGroupAccesses: [],
    userAccesses: [],

    favorites: [],

    program: {
      id: "xvzrp56zKvI",
    },
    displayInList: true,
    sortOrder: 3,
    mandatory: false,
    renderOptionsAsRadio: false,
    searchable: false,
    valueType: "TEXT",
    displayShortName: "Family member details 4.0 UHID",
    displayName: "Family member details 4.0 UHID",
    favorite: false,
    id: "KAmyo4tnJGp",
    attributeValues: [],
    trackedEntityAttribute: {
      formName: "UHID",
      valueType: "TEXT",
      unique: false,
      pattern: "",
      displayName: "UHID",
      displayShortName: "UHID",
      displayFormName: "UHID",
      optionSetValue: false,
      id: "vrM7vt4JZmQ",
      attributeValues: [],
    },
  },
  {
    name: "Family member details 4.0 Name",
    created: "2024-11-20T13:43:38.194",
    lastUpdated: "2024-11-20T14:42:36.511",
    translations: [],
    externalAccess: false,
    userGroupAccesses: [],
    userAccesses: [],

    favorites: [],

    program: {
      id: "xvzrp56zKvI",
    },
    displayInList: true,
    sortOrder: 4,
    mandatory: false,
    renderOptionsAsRadio: false,
    searchable: false,
    valueType: "TEXT",
    displayShortName: "Family member details 4.0 Name",
    displayName: "Family member details 4.0 Name",
    favorite: false,
    id: "NsZx5rdbGRS",
    attributeValues: [],
    trackedEntityAttribute: {
      formName: "Name",
      valueType: "TEXT",
      unique: false,
      pattern: "",
      displayName: "Name",
      displayShortName: "Name",
      displayFormName: "Name",
      optionSetValue: false,
      id: "s7f3ayF0MEG",
      attributeValues: [],
    },
  },
  {
    name: "Family member details 4.0 Date of birth",
    created: "2024-11-20T13:43:38.194",
    lastUpdated: "2024-11-20T14:42:36.511",
    translations: [],
    externalAccess: false,
    userGroupAccesses: [],
    userAccesses: [],

    favorites: [],

    program: {
      id: "xvzrp56zKvI",
    },
    displayInList: true,
    sortOrder: 5,
    mandatory: false,
    renderOptionsAsRadio: false,
    searchable: false,
    valueType: "AGE",
    displayShortName: "Family member details 4.0 Date of birth",
    displayName: "Family member details 4.0 Date of birth",
    favorite: false,
    id: "KGekkAOjdhw",
    attributeValues: [],
    trackedEntityAttribute: {
      formName: "Date of birth",
      valueType: "AGE",
      unique: false,
      pattern: "",
      displayName: "Date of birth",
      displayShortName: "Date of birth",
      displayFormName: "Date of birth",
      optionSetValue: false,
      id: "rB3psCPmxwE",
      attributeValues: [],
    },
  },
  {
    name: "Family member details 4.0 Sex",
    created: "2024-11-20T13:43:38.194",
    lastUpdated: "2024-11-20T14:42:36.511",
    translations: [],
    externalAccess: false,
    userGroupAccesses: [],
    userAccesses: [],

    favorites: [],

    program: {
      id: "xvzrp56zKvI",
    },
    displayInList: true,
    sortOrder: 6,
    mandatory: false,
    renderOptionsAsRadio: false,
    searchable: false,
    valueType: "TEXT",
    displayShortName: "Family member details 4.0 Sex",
    displayName: "Family member details 4.0 Sex",
    favorite: false,
    id: "Fwsx794LLqX",
    attributeValues: [],
    trackedEntityAttribute: {
      formName: "Sex",
      valueType: "TEXT",
      optionSet: {
        code: "Sex",
        name: "Sex",
        translations: [],
        options: [
          {
            code: "Male",
            name: "Male",
            translations: [],
            sortOrder: 1,
            id: "NAfA68NCVFh",
            attributeValues: [],
          },
          {
            code: "Female",
            name: "Female",
            translations: [],
            sortOrder: 2,
            id: "QehEFc5wV5T",
            attributeValues: [],
          },
        ],
        id: "rD9ZqOfGgaS",
        attributeValues: [],
      },
      unique: false,
      pattern: "",
      displayName: "Sex",
      displayShortName: "Sex",
      displayFormName: "Sex",
      optionSetValue: true,
      id: "MYaNKVVYIQT",
      attributeValues: [],
    },
  },
  {
    name: "Family member details 4.0 Contact Number",
    created: "2024-11-20T13:43:38.194",
    lastUpdated: "2024-11-20T14:42:36.511",
    translations: [],
    externalAccess: false,
    userGroupAccesses: [],
    userAccesses: [],

    favorites: [],

    program: {
      id: "xvzrp56zKvI",
    },
    displayInList: true,
    sortOrder: 7,
    mandatory: false,
    renderOptionsAsRadio: false,
    searchable: false,
    valueType: "NUMBER",
    displayShortName: "Family member details 4.0 Contact Number",
    displayName: "Family member details 4.0 Contact Number",
    favorite: false,
    id: "c8Lgoc3vNJi",
    attributeValues: [],
    trackedEntityAttribute: {
      formName: "Contact Number",
      valueType: "NUMBER",
      unique: false,
      pattern: "",
      displayName: "Contact Number",
      displayShortName: "Contact Number",
      displayFormName: "Contact Number",
      optionSetValue: false,
      id: "HyGJqEzbxD4",
      attributeValues: [],
    },
  },
  {
    name: "Family member details 4.0 Unique dwelling ID",
    created: "2024-11-20T13:43:38.194",
    lastUpdated: "2024-11-20T14:42:36.511",
    translations: [],
    externalAccess: false,
    userGroupAccesses: [],
    userAccesses: [],

    favorites: [],

    program: {
      id: "xvzrp56zKvI",
    },
    displayInList: true,
    sortOrder: 8,
    mandatory: false,
    renderOptionsAsRadio: false,
    searchable: false,
    valueType: "TEXT",
    displayShortName: "Family member details 4.0 Unique dwelling ID",
    displayName: "Family member details 4.0 Unique dwelling ID",
    favorite: false,
    id: "ix7lkPzs6XM",
    attributeValues: [],
    trackedEntityAttribute: {
      formName: "Unique dwelling ID",
      valueType: "TEXT",
      unique: false,
      pattern: "",
      displayName: "Unique dwelling ID",
      displayShortName: "Unique dwelling ID",
      displayFormName: "Unique dwelling ID",
      optionSetValue: false,
      id: "hDE1WNqTTwF",
      attributeValues: [],
    },
  },
  {
    dataElement: {
      valueType: "TEXT",
      optionSet: {
        code: "Membership Status",
        name: "Membership Status",
        translations: [],
        options: [
          {
            code: "Present",
            name: "Present",
            translations: [],
            displayName: "Present",
            id: "jIFpYXSw3Gt",
            attributeValues: [],
          },
          {
            code: "Demise",
            name: "Demise",
            translations: [],
            displayName: "Demise",
            id: "HCFYJffamov",
            attributeValues: [],
          },
          {
            code: "Transferred",
            name: "Transferred",
            translations: [],
            displayName: "Transferred",
            id: "rCq4Jte9x3x",
            attributeValues: [],
          },
        ],
        valueType: "TEXT",
        version: 3,
        displayName: "Membership Status",
        id: "p1mPcT964KJ",
        attributeValues: [],
      },
      displayName: "HHM_1 - Membership Status",
      displayShortName: "HHM_1 - Membership Status",
      displayFormName: "Membership Status",
      id: "cP1EanFicmA",
      attributeValues: [
        {
          attribute: {
            id: "KhGyBaFWXZT",
          },
          value: "member_form",
        },
      ],
    },
    compulsory: false,
  },
  // {
  //   code: "sex",
  //   name: "Sex",
  //   id: "w1pdC1I8xsh",
  //   disable: false,
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "M",
  //       label: "Male",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Male"],
  //       translations: {
  //         lo: "ຊາຍ",
  //       },
  //     },
  //     {
  //       value: "F",
  //       label: "Female",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Female"],
  //       translations: {
  //         lo: "ຍິງ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ເພດ",
  //     en: "Sex",
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "firstname",
  //   name: "First name",
  //   id: "gvtjbfq41hn",
  //   disable: false,
  //   valueType: "MASK",
  //   pattern: /^\D+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ຊື່",
  //     en: "First name",
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "lastname",
  //   name: "Last name",
  //   id: "xru22thNYm0",
  //   disable: false,
  //   valueType: "MASK",
  //   pattern: /^\D+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ນາມສະກູນ",
  //     en: "Last name",
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "relation",
  //   name: "Relation with head",
  //   id: "feO2931a74k",
  //   disable: false,
  //   valueType: "TEXT",
  //   existCompulsory: true,
  //   valueSet: [
  //     {
  //       value: "head",
  //       label: "Head of family",
  //       isDisabled: false,
  //       compulsory: true,
  //       unique: true,
  //       multiple: ["Head of family"],
  //       translations: {
  //         lo: "ຫົວໜ້າຄອບຄົວ",
  //         vi: "ຫົວໜ້າຄອບຄົວ",
  //       },
  //     },
  //     {
  //       value: "wife",
  //       label: "Wife",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Wife"],
  //       translations: {
  //         lo: "ເມຍ",
  //         vi: "ເມຍ",
  //       },
  //     },
  //     {
  //       value: "children",
  //       label: "Children",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Children"],
  //       translations: {
  //         lo: "ລູກ",
  //         vi: "ລູກ",
  //       },
  //     },
  //     {
  //       value: "relatives",
  //       label: "Other Relatives",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Other Relatives"],
  //       translations: {
  //         lo: "ຍາດພີ່ນ້ອງ",
  //         vi: "ຍາດພີ່ນ້ອງ",
  //       },
  //     },
  //     {
  //       value: "parent",
  //       label: "Parents",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Parents"],
  //       translations: {
  //         lo: "ພໍ່ແມ່",
  //         vi: "ພໍ່ແມ່",
  //       },
  //     },
  //     {
  //       value: "others",
  //       label: "Others",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Others"],
  //       translations: {
  //         lo: "ອື່ນໆ",
  //         vi: "ອື່ນໆ",
  //       },
  //     },
  //   ],
  //   sort: "true",
  //   translations: {
  //     lo: "ສາຍພົວພັນກັບຫົວໜ້າຄອບຄົວ",
  //     en: "Relation with head",
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "ethnicity",
  //   name: "Ethnicity",
  //   id: "xee9ddPU5eI",
  //   disable: false,
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "ລາວ",
  //       label: "Lao",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ລາວ"],
  //       translations: {
  //         lo: "ລາວ",
  //       },
  //     },
  //     {
  //       value: "ໄຕ",
  //       label: "Tai",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ໄຕ"],
  //       translations: {
  //         lo: "ໄຕ",
  //       },
  //     },
  //     {
  //       value: "ຜູ້ໄທ",
  //       label: "Phouthai",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຜູ້ໄທ"],
  //       translations: {
  //         lo: "ຜູ້ໄທ",
  //       },
  //     },
  //     {
  //       value: "ລື້",
  //       label: "Lue",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ລື້"],
  //       translations: {
  //         lo: "ລື້",
  //       },
  //     },
  //     {
  //       value: "ຍວນ",
  //       label: "Nyouan",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຍວນ"],
  //       translations: {
  //         lo: "ຍວນ",
  //       },
  //     },
  //     {
  //       value: "ຢັ້ງ",
  //       label: "Nyung",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຢັ້ງ"],
  //       translations: {
  //         lo: "ຢັ້ງ",
  //       },
  //     },
  //     {
  //       value: "ແຊກ",
  //       label: "Xek",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ແຊກ"],
  //       translations: {
  //         lo: "ແຊກ",
  //       },
  //     },
  //     {
  //       value: "ໄທເໜືອ",
  //       label: "Thai-nua",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ໄທເໜືອ"],
  //       translations: {
  //         lo: "ໄທເໜືອ",
  //       },
  //     },
  //     {
  //       value: "ກຶມມຸ",
  //       label: "Khmou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ກຶມມຸ"],
  //       translations: {
  //         lo: "ກຶມມຸ",
  //       },
  //     },
  //     {
  //       value: "ໄປຣ",
  //       label: "Prai",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ໄປຣ"],
  //       translations: {
  //         lo: "ໄປຣ",
  //       },
  //     },
  //     {
  //       value: "ຊິງມູນ",
  //       label: "Xingmoun",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຊິງມູນ"],
  //       translations: {
  //         lo: "ຊິງມູນ",
  //       },
  //     },
  //     {
  //       value: "ຜ້ອງ",
  //       label: "Phong",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຜ້ອງ"],
  //       translations: {
  //         lo: "ຜ້ອງ",
  //       },
  //     },
  //     {
  //       value: "ແທ່ນ",
  //       label: "Then",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ແທ່ນ"],
  //       translations: {
  //         lo: "ແທ່ນ",
  //       },
  //     },
  //     {
  //       value: "ເອີດູ",
  //       label: "Oeu-dou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ເອີດູ"],
  //       translations: {
  //         lo: "ເອີດູ",
  //       },
  //     },
  //     {
  //       value: "ບິດ",
  //       label: "Bid",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ບິດ"],
  //       translations: {
  //         lo: "ບິດ",
  //       },
  //     },
  //     {
  //       value: "ລະເມດ",
  //       label: "Lamed",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ລະເມດ"],
  //       translations: {
  //         lo: "ລະເມດ",
  //       },
  //     },
  //     {
  //       value: "ສາມຕ່າວ",
  //       label: "Samtao",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ສາມຕ່າວ"],
  //       translations: {
  //         lo: "ສາມຕ່າວ",
  //       },
  //     },
  //     {
  //       value: "ກະຕ່າງ",
  //       label: "Ka-tang",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ກະຕ່າງ"],
  //       translations: {
  //         lo: "ກະຕ່າງ",
  //       },
  //     },
  //     {
  //       value: "ມະກອງ",
  //       label: "Makong",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ມະກອງ"],
  //       translations: {
  //         lo: "ມະກອງ",
  //       },
  //     },
  //     {
  //       value: "ຕຣີ",
  //       label: "Tri",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຕຣີ"],
  //       translations: {
  //         lo: "ຕຣີ",
  //       },
  //     },
  //     {
  //       value: "ຢຣຸ",
  //       label: "Nyrou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຢຣຸ"],
  //       translations: {
  //         lo: "ຢຣຸ",
  //       },
  //     },
  //     {
  //       value: "ຕຣຽງ",
  //       label: "Triang",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຕຣຽງ"],
  //       translations: {
  //         lo: "ຕຣຽງ",
  //       },
  //     },
  //     {
  //       value: "ຕະໂອ້ຍ",
  //       label: "Ta-oy",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຕະໂອ້ຍ"],
  //       translations: {
  //         lo: "ຕະໂອ້ຍ",
  //       },
  //     },
  //     {
  //       value: "ແຢະ",
  //       label: "Nyeh",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ແຢະ"],
  //       translations: {
  //         lo: "ແຢະ",
  //       },
  //     },
  //     {
  //       value: "ເບຣົາ",
  //       label: "Brao",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ເບຣົາ"],
  //       translations: {
  //         lo: "ເບຣົາ",
  //       },
  //     },
  //     {
  //       value: "ກະຕູ",
  //       label: "Katou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ກະຕູ"],
  //       translations: {
  //         lo: "ກະຕູ",
  //       },
  //     },
  //     {
  //       value: "ຮາຮັກ",
  //       label: "Harak",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຮາຮັກ"],
  //       translations: {
  //         lo: "ຮາຮັກ",
  //       },
  //     },
  //     {
  //       value: "ໂອຍ",
  //       label: "Oy",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ໂອຍ"],
  //       translations: {
  //         lo: "ໂອຍ",
  //       },
  //     },
  //     {
  //       value: "ກຣຽງ",
  //       label: "Kriang",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ກຣຽງ"],
  //       translations: {
  //         lo: "ກຣຽງ",
  //       },
  //     },
  //     {
  //       value: "ເຈັງ",
  //       label: "Cheng",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ເຈັງ"],
  //       translations: {
  //         lo: "ເຈັງ",
  //       },
  //     },
  //     {
  //       value: "ສະດ່າງ",
  //       label: "Sadang",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ສະດ່າງ"],
  //       translations: {
  //         lo: "ສະດ່າງ",
  //       },
  //     },
  //     {
  //       value: "ຊ່ວຍ",
  //       label: "Xouay",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຊ່ວຍ"],
  //       translations: {
  //         lo: "ຊ່ວຍ",
  //       },
  //     },
  //     {
  //       value: "ຍະເຫີນ",
  //       label: "Nyaheun",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຍະເຫີນ"],
  //       translations: {
  //         lo: "ຍະເຫີນ",
  //       },
  //     },
  //     {
  //       value: "ລະວີ",
  //       label: "Lavi",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ລະວີ"],
  //       translations: {
  //         lo: "ລະວີ",
  //       },
  //     },
  //     {
  //       value: "ປະໂກະ",
  //       label: "Pako",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ປະໂກະ"],
  //       translations: {
  //         lo: "ປະໂກະ",
  //       },
  //     },
  //     {
  //       value: "ຂະແມ່",
  //       label: "Kha-meh",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຂະແມ່"],
  //       translations: {
  //         lo: "ຂະແມ່",
  //       },
  //     },
  //     {
  //       value: "ຕຸ້ມ",
  //       label: "Toum",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຕຸ້ມ"],
  //       translations: {
  //         lo: "ຕຸ້ມ",
  //       },
  //     },
  //     {
  //       value: "ງວນ",
  //       label: "Ngouan",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ງວນ"],
  //       translations: {
  //         lo: "ງວນ",
  //       },
  //     },
  //     {
  //       value: "ມ້ອຍ",
  //       label: "Moy",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ມ້ອຍ"],
  //       translations: {
  //         lo: "ມ້ອຍ",
  //       },
  //     },
  //     {
  //       value: "ກຣີ",
  //       label: "Kri",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ກຣີ"],
  //       translations: {
  //         lo: "ກຣີ",
  //       },
  //     },
  //     {
  //       value: "ມົ້ງ",
  //       label: "Hmong",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ມົ້ງ"],
  //       translations: {
  //         lo: "ມົ້ງ",
  //       },
  //     },
  //     {
  //       value: "ອີວມຽນ",
  //       label: "Eio-miang",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ອີວມຽນ"],
  //       translations: {
  //         lo: "ອີວມຽນ",
  //       },
  //     },
  //     {
  //       value: "ອາຄາ",
  //       label: "Akha",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ອາຄາ"],
  //       translations: {
  //         lo: "ອາຄາ",
  //       },
  //     },
  //     {
  //       value: "ພູນ້ອຍ",
  //       label: "Phou-noy",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ພູນ້ອຍ"],
  //       translations: {
  //         lo: "ພູນ້ອຍ",
  //       },
  //     },
  //     {
  //       value: "ລາຫູ",
  //       label: "Lahou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ລາຫູ"],
  //       translations: {
  //         lo: "ລາຫູ",
  //       },
  //     },
  //     {
  //       value: "ສີລາ",
  //       label: "Sila",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ສີລາ"],
  //       translations: {
  //         lo: "ສີລາ",
  //       },
  //     },
  //     {
  //       value: "ຮາຍີ",
  //       label: "Hayi",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຮາຍີ"],
  //       translations: {
  //         lo: "ຮາຍີ",
  //       },
  //     },
  //     {
  //       value: "ໂລໂລ",
  //       label: "Lolo",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ໂລໂລ"],
  //       translations: {
  //         lo: "ໂລໂລ",
  //       },
  //     },
  //     {
  //       value: "ຫໍ້",
  //       label: "Ho",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຫໍ້"],
  //       translations: {
  //         lo: "ຫໍ້",
  //       },
  //     },
  //     {
  //       value: "ບຣູ",
  //       label: "Brou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ບຣູ"],
  //       translations: {
  //         lo: "ບຣູ",
  //       },
  //     },
  //     {
  //       value: "ອື່ນໆ",
  //       label: "Others",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ອື່ນໆ"],
  //       translations: {
  //         lo: "ອື່ນໆ",
  //       },
  //     },
  //     {
  //       value: "ບໍ່ບອກ",
  //       label: "Not applicable",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ບໍ່ບອກ"],
  //       translations: {
  //         lo: "ບໍ່ບອກ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ຊົນເຜົ່າ",
  //     en: "Ethnicity",
  //   },
  //   compulsory: true,
  // },
  // // newFamilyBookNumber
  // {
  //   code: "newFamilyBookNum",
  //   name: "New Family Book Number",
  //   id: "W4aInCTn8p5",
  //   disable: false,
  //   valueType: "TEXT",
  //   // pattern: /^[a-zA-Z\s]+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ເລກປະຈຳໂຕຢູ່ປຶືມສຳມະໂນຄົວ",
  //     en: "New Family Book Number",
  //   },
  //   compulsory: false,
  // },
  // // covid number
  // {
  //   code: "covidNum",
  //   name: "Covid Number",
  //   id: "rSETgSvyVpJ",
  //   disable: false,
  //   valueType: "TEXT",
  //   // pattern: /^[a-zA-Z\s]+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ເລກບັດຮັບວັກຊີນໂຄວິດ",
  //     en: "Covid Number",
  //   },
  //   compulsory: false,
  // },
  // // police number
  // {
  //   code: "policeNum",
  //   name: "Police Number",
  //   id: "PYgXM3R2TQd",
  //   disable: false,
  //   valueType: "MASK",
  //   pattern: /^\d+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ເລກບັດປະຈຳໂຕ",
  //     en: "Police Number",
  //   },
  //   compulsory: false,
  // },
  // // phone number
  // {
  //   code: "phoneNum",
  //   name: "Phone Number",
  //   id: "g9wNk1T3MLE",
  //   disable: false,
  //   valueType: "MASK",
  //   pattern: /^[0-9]+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ເບີໂທຕິດຕໍ່",
  //     en: "Phone Number",
  //   },
  //   compulsory: false,
  // },
  // {
  //   code: "nationality",
  //   name: "Nationality",
  //   id: "SpuwXA7NHUG",
  //   disable: false,
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "lao",
  //       label: "Lao",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Lao"],
  //       translations: {
  //         lo: "ລາວ",
  //       },
  //     },
  //     {
  //       value: "others",
  //       label: "Other Nationality",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Other Nationality"],
  //       translations: {
  //         lo: "ສັນຊາດອື່ນໆ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ສັນຊາດ",
  //     en: "Nationality",
  //   },
  //   formatter: (cellContent, row, rowIndex, extraData) => {
  //     return rowIndex + 1;
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "education",
  //   name: "Highest Education",
  //   id: "amhDvtb0SpN",
  //   disable: false,
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "primary-school",
  //       label: "Primary school",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Primary school"],
  //       translations: {
  //         lo: "ປະຖົມ",
  //       },
  //     },
  //     {
  //       value: "secondary-school",
  //       label: "Secondary School",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Secondary School"],
  //       translations: {
  //         lo: "ມັດທະຍົມຕົ້ນ",
  //       },
  //     },
  //     {
  //       value: "high-school",
  //       label: "High School",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["High School"],
  //       translations: {
  //         lo: "ມັດທະຍົມປາຍ",
  //       },
  //     },
  //     {
  //       value: "vocational",
  //       label: "Vocational or higher",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Vocational or higher"],
  //       translations: {
  //         lo: "ວິຊາຊີບຊັ້ນກາງ ຫຼື ຊັ້ນສູງ",
  //       },
  //     },
  //     {
  //       value: "bachelor",
  //       label: "Bachelor degree",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Bachelor degree"],
  //       translations: {
  //         lo: "ປະລິນຍາຕີ",
  //       },
  //     },
  //     {
  //       value: "bachelor-high",
  //       label: "Higher bachelor degree",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Higher bachelor degree"],
  //       translations: {
  //         lo: "ເໜືອປະລິນຍາຕີ",
  //       },
  //     },
  //     {
  //       value: "none",
  //       label: "None",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["None Education"],
  //       translations: {
  //         lo: "ບໍ່ມີການສຶກສາ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ລະດັບການສຶກສາ",
  //     en: "Highest Education",
  //   },
  // },
  // {
  //   code: "insurance",
  //   name: "Type of Insurance scheme",
  //   id: "btOLqyQrrXf",
  //   disable: false,
  //   valueType: "TEXT",
  //   compulsory: true,
  //   valueSet: [
  //     {
  //       value: "a1",
  //       label: "SASS",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["SASS"],
  //       translations: {
  //         lo: "ປະກັນສັງຄົມພາກລັດຖະກອນ (ອປລ)",
  //       },
  //     },
  //     {
  //       value: "a2",
  //       label: "SSO",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["SSO"],
  //       translations: {
  //         lo: "ປະກັນສັງຄົມພາກເອກະຊົນ (ອປສ)",
  //       },
  //     },
  //     {
  //       value: "b",
  //       label: "Military/Police Scheme",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Military/Police Scheme"],
  //       translations: {
  //         lo: "ປະກັນສັງຄົມຂອງທະຫານ (ພາກ ກປຊ)/ປະກັນສັງຄົມຂອງທະຫານ (ພາກ ກປສ)",
  //       },
  //     },
  //     {
  //       value: "c",
  //       label: "National Health Insurance",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["National Health Insurance"],
  //       translations: {
  //         lo: "ປະກັນສຸຂະພາບແຫ່ງຊາດ/NHI (ກປຊ)",
  //       },
  //     },
  //     {
  //       value: "d",
  //       label: "Community-based Health Insurance",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Community-based Health Insurance"],
  //       translations: {
  //         lo: "ກອງທຶນປະກັນສຸຂະພາບຊຸມຊົນ (ຄປສຊ)",
  //       },
  //     },
  //     // {
  //     //   value: "e",
  //     //   label: "Private Health Insurance",
  //     //   isDisabled: false,
  //     //   unique: false,
  //     //   multiple: ["Private Health Insurance"],
  //     //   translations: {
  //     //     lo: "ປະກັນສຸຂະພາບເອກະຊົນ",
  //     //   },
  //     // },
  //     {
  //       value: "g",
  //       label: "Dont Know",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Dont Know"],
  //       translations: {
  //         lo: "ບໍ່ຮູ້",
  //       },
  //     },
  //     {
  //       value: "f",
  //       label: "Dont have",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Dont have"],
  //       translations: {
  //         lo: "ບໍ່ໄດ້ເຂົ້າປະກັນສຸຂະພາບ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ປະເພດປະກັນສຸຂະພາບ",
  //     en: "Type of Insurance scheme",
  //   },
  // },
  // {
  //   code: "maritalstatus",
  //   name: "Marital status",
  //   id: "xXybyxfggiE",
  //   disable: false,
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "S",
  //       label: "Never marry",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Never marry"],
  //       translations: {
  //         lo: "ບໍ່ເຄີຍແຕ່ງດອງ",
  //       },
  //     },
  //     {
  //       value: "M",
  //       label: "Marriage",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Marriage"],
  //       translations: {
  //         lo: "ແຕ່ງດອງ",
  //       },
  //     },
  //     {
  //       value: "D",
  //       label: "Divorce",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Divorce"],
  //       translations: {
  //         lo: "ຢ່າຮ້າງ",
  //       },
  //     },
  //     {
  //       value: "SE",
  //       label: "Separated",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Separated"],
  //       translations: {
  //         lo: "ແຍກກັນຢູ່",
  //       },
  //     },
  //     {
  //       value: "W",
  //       label: "Widow",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Widow"],
  //       translations: {
  //         lo: "ໝ້າຍ",
  //       },
  //     },
  //     {
  //       value: "C",
  //       label: "Cohabit",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Cohabit"],
  //       translations: {
  //         lo: "ຢູ່ຮ່ວມກັນ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ສະພາບສົມລົດ",
  //     en: "Marital status",
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "agetype",
  //   name: "Type of Age",
  //   id: "Mn6DGipd0yD",
  //   disable: false,
  //   hidden: false,
  //   hiddenCol: true,
  //   valueType: "TEXT",
  //   compulsory: true,
  //   valueSet: [
  //     {
  //       value: "DOB",
  //       label: "Date of birth",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Date of birth"],
  //       translations: {
  //         lo: "ວັນເດືອນປີເກີດ",
  //       },
  //     },
  //     {
  //       value: "birthyear",
  //       label: "Birth Year",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Birth Year"],
  //       translations: {
  //         lo: "ປີເກີດ",
  //       },
  //     },
  //     /**
  //      * Temp turn off to avoid user enter this data, it hard to auto age increment
  //      *  */
  //     // {
  //     //   value: "age",
  //     //   label: "Age in years",
  //     //   isDisabled: false,
  //     //   unique: false,
  //     //   multiple: ["Age in years"],
  //     //   translations: {
  //     //     lo: "ອາຍຸ(ປີ)",
  //     //   },
  //     // },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ອາຍຸ(ປີ)",
  //     en: "Type of Age",
  //   },
  // },
  // {
  //   code: "DOB",
  //   name: "Date of birth",
  //   id: "fqy4x9rbdGi",
  //   disable: false,
  //   hidden: true,
  //   hiddenCol: true,
  //   valueType: "DATE",
  //   sort: null,
  //   translations: {
  //     lo: "ວັນເດືອນປີເກີດ",
  //     en: "Date of birth",
  //   },
  // },
  // {
  //   code: "birthyear",
  //   name: "Birth Year",
  //   id: "J9UdB29DZnl",
  //   disable: false,
  //   hidden: true,
  //   hiddenCol: true,
  //   valueType: "DATE",
  //   periodType: "year", //https://material-ui-pickers.dev/api/KeyboardDatePicker
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ປີເກີດ",
  //     en: "Birth Year",
  //   },
  // },
  // {
  //   code: "age",
  //   name: "Age in years",
  //   id: "Mn6DGipd0yE",
  //   disable: false,
  //   hiddenCol: true,
  //   hidden: true,
  //   valueType: "NUMBER",
  //   attribute: {
  //     maxLength: 3,
  //     max: 120,
  //   },
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ອາຍຸ(ປີ)",
  //     en: "Age in years",
  //   },
  // },
  // // {
  // //   code: "age",
  // //   name: "Age",
  // //   id: "age",
  // //   valueType: "TEXT",
  // //   additionCol: true,
  // //   valueSet: null,
  // //   hiddenCol: true,
  // //   sort: null,
  // //   translations: {
  // //     lo: "ອາຍຸ",
  // //     en: "Age",
  // //   },
  // // },
  // {
  //   code: "status",
  //   name: "Status",
  //   id: "K9UdB29DZnl",
  //   disable: false,
  //   hidden: false,
  //   valueType: "TEXT",
  //   defaultValue: "Active",
  //   valueSet: [
  //     {
  //       value: "active",
  //       label: "Active",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Active"],
  //       translations: {
  //         lo: "ມີໜ້າໃນຄອບຄົວ",
  //       },
  //     },
  //     {
  //       value: "transfer-out",
  //       label: "Transferred",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Transferred"],
  //       translations: {
  //         lo: "ຍ້າຍອອກ",
  //       },
  //     },
  //     {
  //       value: "dead",
  //       label: "Dead",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Dead"],
  //       translations: {
  //         lo: "ເສຍຊີວິດ",
  //       },
  //     },
  //     {
  //       value: "not-residing",
  //       label: "Not residing",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Not residing"],
  //       translations: {
  //         lo: "ຢູ່ນອກປະເທດ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ສະຖານະ",
  //     en: "Status",
  //   },
  // },
];

export default originMetadata;
