const originMetadata = [
  {
    compulsory: false,
    code: "CADfVSQEVVi",
    displayName: "ID type",
    displayFormName: "ID type",
    valueType: "TEXT",
    valueSet: [
      {
        value: "CID",
        label: "CID",
        translations: {
          lo: "CID",
        },
      },
      {
        value: "Green Card Holder",
        label: "Green Card Holder",
      },
      {
        value: "Marriage Certificate",
        label: "Marriage Certificate",
      },
      {
        value: "MCH no.",
        label: "MCH no.",
      },
      {
        value: "Passport",
        label: "Passport",
      },
    ],
    displayInList: true,
  },
  // {
  //   compulsory: false,
  //   id: "rOA2ACbkXug",
  //   displayName: "Country ID",
  //   displayFormName: "Country ID",
  //   valueType: "TEXT",
  //   valueSet: null,
  //   displayInList: true,
  // },
  // {
  //   compulsory: false,
  //   id: "vrM7vt4JZmQ",
  //   displayName: "UHID",
  //   displayFormName: "UHID",
  //   valueType: "TEXT",
  //   valueSet: null,
  //   displayInList: true,
  // },
  // {
  //   compulsory: false,
  //   id: "s7f3ayF0MEG",
  //   displayName: "Name",
  //   displayFormName: "Name",
  //   valueType: "TEXT",
  //   valueSet: null,
  //   displayInList: true,
  // },
  // {
  //   compulsory: false,
  //   id: "rB3psCPmxwE",
  //   displayName: "Date of birth",
  //   displayFormName: "Date of birth",
  //   valueType: "AGE",
  //   valueSet: null,
  //   displayInList: true,
  // },
  // {
  //   compulsory: false,
  //   id: "MYaNKVVYIQT",
  //   displayName: "Sex",
  //   displayFormName: "Sex",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "Male",
  //       label: "Male",
  //     },
  //     {
  //       value: "Female",
  //       label: "Female",
  //     },
  //   ],
  //   displayInList: true,
  // },
  // {
  //   compulsory: false,
  //   id: "HyGJqEzbxD4",
  //   displayName: "Contact Number",
  //   displayFormName: "Contact Number",
  //   valueType: "NUMBER",
  //   valueSet: null,
  //   displayInList: true,
  // },
  // {
  //   compulsory: false,
  //   id: "hDE1WNqTTwF",
  //   displayName: "Unique dwelling ID",
  //   displayFormName: "Unique dwelling ID",
  //   valueType: "TEXT",
  //   valueSet: null,
  //   displayInList: true,
  // },
  // {
  //   compulsory: false,
  //   id: "dzeTdP1U1b1",
  //   displayName: "HHM_1 - Age at death",
  //   displayFormName: "Age at death",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "LyBiqvOGFGc",
  //   displayName: "HHM_1 - Age at first marriage or first living together",
  //   displayFormName: "Age at first marriage or first living together",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "JgHcoI8Vs9v",
  //   displayName: "HHM_1 - ANC availed during recent pregnancy",
  //   displayFormName: "Was ANC availed during the recent pregnancy",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "Yes",
  //       label: "Yes",
  //     },
  //     {
  //       value: "No",
  //       label: "No",
  //     },
  //     {
  //       value: "N/A",
  //       label: "N/A",
  //     },
  //     {
  //       value: "Don't know",
  //       label: "Don't know",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "e0Tg69b3KDD",
  //   displayName: "HHM_1 - Assistance for walking received",
  //   displayFormName: "use any equipment or receive assistance for walking?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "DPlIkV0XnI8",
  //   displayName: "HHM_1 - Attending traditional learning",
  //   displayFormName:
  //     "Is/has attending/attended any other types of traditional learning?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "None or never attended monastic education",
  //       label: "None or never attended monastic education",
  //     },
  //     {
  //       value:
  //         "Formal Monastic Education (Lobdra, Dratshang, Shedra, Pāṭashālā, Vidyālaya, etc)",
  //       label:
  //         "Formal Monastic Education (Lobdra, Dratshang, Shedra, Pāṭashālā, Vidyālaya, etc)",
  //     },
  //     {
  //       value:
  //         "Informal Monastic Education(Informal learning from Lama/others,etc)",
  //       label:
  //         "Informal Monastic Education(Informal learning from Lama/others,etc)",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "kzp9TltHi2M",
  //   displayName: "HHM_1 - Beats per minute_1",
  //   displayFormName: "Beats per minute",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "JJoDq26kmmy",
  //   displayName: "HHM_1 - Beats per minute_2",
  //   displayFormName: "Beats per minute",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "whGSwuEwp6B",
  //   displayName: "HHM_1 - Beats per minute_3",
  //   displayFormName: "Beats per minute",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "Z4zfIkKCP7R",
  //   displayName: "HHM_1 - Currently pregnant",
  //   displayFormName: "Is she currently pregnant",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "Yes",
  //       label: "Yes",
  //     },
  //     {
  //       value: "No",
  //       label: "No",
  //     },
  //     {
  //       value: "N/A",
  //       label: "N/A",
  //     },
  //     {
  //       value: "Don't know",
  //       label: "Don't know",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "ycGbZeG8LeX",
  //   displayName: "HHM_1 - Current Marital status",
  //   displayFormName: "Current Marital status",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "Never married",
  //       label: "Never married",
  //     },
  //     {
  //       value: "Living together",
  //       label: "Living together",
  //     },
  //     {
  //       value: "Married",
  //       label: "Married",
  //     },
  //     {
  //       value: "Divorced",
  //       label: "Divorced",
  //     },
  //     {
  //       value: "Separated",
  //       label: "Separated",
  //     },
  //     {
  //       value: "Widow/Widower",
  //       label: "Widow/Widower",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "McJaMbzcxAS",
  //   displayName: "HHM_1 - Date of Death",
  //   displayFormName: "Date of Death",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "XpnpuBUtcT2",
  //   displayName: "HHM_1 - Death alcohol related",
  //   displayFormName: "Was the death alcohol related?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "Yes",
  //       label: "Yes",
  //     },
  //     {
  //       value: "No",
  //       label: "No",
  //     },
  //     {
  //       value: "N/A",
  //       label: "N/A",
  //     },
  //     {
  //       value: "Don't know",
  //       label: "Don't know",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "RDXCYFo4Uv8",
  //   displayName: "HHM_1 - Diastolic (mmHg)_1",
  //   displayFormName: "Diastolic (mmHg)",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ofyknwue3kI",
  //   displayName: "HHM_1 - Diastolic (mmHg)_2",
  //   displayFormName: "Diastolic (mmHg)",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "Bf0l1lc8HdR",
  //   displayName: "HHM_1 - Diastolic (mmHg)_3",
  //   displayFormName: "Diastolic (mmHg)",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "blkMcSWuz4L",
  //   displayName: "HHM_1 - Difficulty communicating",
  //   displayFormName:
  //     "has difficulty speaking, communicating, for example, understanding or being understood even if using his/her usual language?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "No difficulty",
  //       label: "No difficulty",
  //     },
  //     {
  //       value: "Yes, Some difficulty",
  //       label: "Yes, Some difficulty",
  //     },
  //     {
  //       value: "Yes, a lot of difficulty",
  //       label: "Yes, a lot of difficulty",
  //     },
  //     {
  //       value: "Cannot speak or communicate at all",
  //       label: "Cannot speak or communicate at all",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "ejY7zEReQea",
  //   displayName: "HHM_1 - Difficulty concentrating",
  //   displayFormName: "has difficulty remembering or concentrating?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "No difficulty",
  //       label: "No difficulty",
  //     },
  //     {
  //       value: "Yes, Some difficulty",
  //       label: "Yes, Some difficulty",
  //     },
  //     {
  //       value: "Yes, a lot of difficulty",
  //       label: "Yes, a lot of difficulty",
  //     },
  //     {
  //       value: "Cannot remember or concentrate at all",
  //       label: "Cannot remember or concentrate at all",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "jrOVR4fNd3H",
  //   displayName: "HHM_1 - Difficulty hearing",
  //   displayFormName: "has difficulty hearing?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "No difficulty",
  //       label: "No difficulty",
  //     },
  //     {
  //       value: "Yes, Some difficulty",
  //       label: "Yes, Some difficulty",
  //     },
  //     {
  //       value: "Yes, a lot of difficulty",
  //       label: "Yes, a lot of difficulty",
  //     },
  //     {
  //       value: "Cannot hear at all",
  //       label: "Cannot hear at all",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "jQ83rALANCm",
  //   displayName: "HHM_1 - Difficulty hearing with hearing aid",
  //   displayFormName: "has difficulty hearing, [even if using a hearing aid]?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "No difficulty",
  //       label: "No difficulty",
  //     },
  //     {
  //       value: "Yes, Some difficulty",
  //       label: "Yes, Some difficulty",
  //     },
  //     {
  //       value: "Yes, a lot of difficulty",
  //       label: "Yes, a lot of difficulty",
  //     },
  //     {
  //       value: "Cannot hear at all",
  //       label: "Cannot hear at all",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "NsyZ9HTZMMa",
  //   displayName: "HHM_1 - Difficulty seeing",
  //   displayFormName: "Has difficulty seeing?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "No difficulty",
  //       label: "No difficulty",
  //     },
  //     {
  //       value: "Yes, Some difficulty",
  //       label: "Yes, Some difficulty",
  //     },
  //     {
  //       value: "Yes, a lot of difficulty",
  //       label: "Yes, a lot of difficulty",
  //     },
  //     {
  //       value: "Cannot see at all",
  //       label: "Cannot see at all",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "DKT4HMi6oSn",
  //   displayName: "HHM_1 - Difficulty seeing with glasses",
  //   displayFormName:
  //     "has difficulty seeing, even if using glasses or contact lenses?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "No difficulty",
  //       label: "No difficulty",
  //     },
  //     {
  //       value: "Yes, Some difficulty",
  //       label: "Yes, Some difficulty",
  //     },
  //     {
  //       value: "Yes, a lot of difficulty",
  //       label: "Yes, a lot of difficulty",
  //     },
  //     {
  //       value: "Cannot see at all",
  //       label: "Cannot see at all",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "KrSqdwQgJoe",
  //   displayName: "HHM_1 - Difficulty walking",
  //   displayFormName: "has  difficulty walking?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "No difficulty",
  //       label: "No difficulty",
  //     },
  //     {
  //       value: "Yes, Some difficulty",
  //       label: "Yes, Some difficulty",
  //     },
  //     {
  //       value: "Yes, a lot of difficulty",
  //       label: "Yes, a lot of difficulty",
  //     },
  //     {
  //       value: "Cannot remember or concentrate at all",
  //       label: "Cannot remember or concentrate at all",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "hf97Ye9CrT4",
  //   displayName: "HHM_1 - Difficulty with self-care",
  //   displayFormName:
  //     "has difficulty with self-care such as washing all over or dressing?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "No difficulty",
  //       label: "No difficulty",
  //     },
  //     {
  //       value: "Yes, Some difficulty",
  //       label: "Yes, Some difficulty",
  //     },
  //     {
  //       value: "Yes, a lot of difficulty",
  //       label: "Yes, a lot of difficulty",
  //     },
  //     {
  //       value: "Cannot do at all",
  //       label: "Cannot do at all",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "tSkN17334Pz",
  //   displayName: "HHM_1 - Glasses or contact lenses",
  //   displayFormName: "Wear glasses or contact lenses?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "toFNuY0zR2a",
  //   displayName: "HHM_1 - H. pylori screening",
  //   displayFormName:
  //     "Has a doctor or other healthcare worker ever screened him/her for H. pylori infection?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "A7UlEPDnV3C",
  //   displayName: "HHM_1 - If Accidental",
  //   displayFormName: "If Accidental",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "Traffic Death",
  //       label: "Traffic Death",
  //     },
  //     {
  //       value: "Natural calamities or disaster",
  //       label: "Natural calamities or disaster",
  //     },
  //     {
  //       value: "Encounters with animals",
  //       label: "Encounters with animals",
  //     },
  //     {
  //       value: "Poisoning (unintentional)",
  //       label: "Poisoning (unintentional)",
  //     },
  //     {
  //       value: "Related to illicit drug or excessive medication use",
  //       label: "Related to illicit drug or excessive medication use",
  //     },
  //     {
  //       value: "Complication of Therapy Deaths",
  //       label: "Complication of Therapy Deaths",
  //     },
  //     {
  //       value: "Others",
  //       label: "Others",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "BdVVPG3a82M",
  //   displayName: "HHM_1 - Immunization received by child",
  //   displayFormName: "Did the child ever receive any schedule immunization",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "VQRxvN71m5l",
  //   displayName: "HHM_1 - Last year pregnancy outcome",
  //   displayFormName:
  //     "Did she have any pregnancy outcomes (delivery, stillbirth, miscarriage) last year ",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "jeDxGYlYBPx",
  //   displayName: "HHM_1 - Latest breast cancer test year",
  //   displayFormName:
  //     "When was her most recent test for breast cancer (Specify year)",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "jswy7SbqErA",
  //   displayName: "HHM_1 - Live births last year",
  //   displayFormName: "Number of live birth last year:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ztinvfhAZnN",
  //   displayName: "HHM_1 - Location of death",
  //   displayFormName: "Where did he/she pass away?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "Health Facilities",
  //       label: "Health Facilities",
  //     },
  //     {
  //       value: "Home",
  //       label: "Home",
  //     },
  //     {
  //       value: "Don't Know",
  //       label: "Don't Know",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "KZbBK7iKP3T",
  //   displayName: "HHM_1 - Manner of Death",
  //   displayFormName: "Manner of Death",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value:
  //         "Natural (illness and its complications, or internal body malfunctions, and is not directly caused by external forces other than infectious diseases)",
  //       label:
  //         "Natural (illness and its complications, or internal body malfunctions, and is not directly caused by external forces other than infectious diseases)",
  //     },
  //     {
  //       value: "Accidental",
  //       label: "Accidental",
  //     },
  //     {
  //       value: "Suicide",
  //       label: "Suicide",
  //     },
  //     {
  //       value: "Homicide",
  //       label: "Homicide",
  //     },
  //     {
  //       value: "Undetermined",
  //       label: "Undetermined",
  //     },
  //     {
  //       value: "Pending (investigation ongoing)",
  //       label: "Pending (investigation ongoing)",
  //     },
  //   ],
  // },
  // {
  //   compulsory: true,
  //   id: "cP1EanFicmA",
  //   displayName: "HHM_1 - Membership Status",
  //   displayFormName: "Membership Status",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "Present",
  //       label: "Present",
  //     },
  //     {
  //       value: "Demise",
  //       label: "Demise",
  //     },
  //     {
  //       value: "Transferred",
  //       label: "Transferred",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "UjLxTtDk9qc",
  //   displayName: "HHM_1 - Miscarriage or abortion last year",
  //   displayFormName: "Number of miscarriage or abortion last year:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "kcJX2YCBB3v",
  //   displayName: "HHM_1 - Modern Education",
  //   displayFormName: "Highest level of Modern Education",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "None or Never attended modern education",
  //       label: "None or Never attended modern education",
  //     },
  //     {
  //       value: "Non-Formal Education (NFE)",
  //       label: "Non-Formal Education (NFE)",
  //     },
  //     {
  //       value: "Early Childhood Care and Development (ECCD)",
  //       label: "Early Childhood Care and Development (ECCD)",
  //     },
  //     {
  //       value: "Primary Education (Class PP-VI)",
  //       label: "Primary Education (Class PP-VI)",
  //     },
  //     {
  //       value: "Lower Secondary Education (Class VII-VIII)",
  //       label: "Lower Secondary Education (Class VII-VIII)",
  //     },
  //     {
  //       value: "Middle Secondary Education (Class IX-X)",
  //       label: "Middle Secondary Education (Class IX-X)",
  //     },
  //     {
  //       value: "Higher Secondary Education (Class XI-XII)",
  //       label: "Higher Secondary Education (Class XI-XII)",
  //     },
  //     {
  //       value:
  //         "Technical and Vocational Education Training (TVET) or equivalent",
  //       label:
  //         "Technical and Vocational Education Training (TVET) or equivalent",
  //     },
  //     {
  //       value:
  //         "Tertiary Education (Diploma, Bachelor's degree, Master’s degree and Doctoral or equivalent level, which are usually provided by universities)",
  //       label:
  //         "Tertiary Education (Diploma, Bachelor's degree, Master’s degree and Doctoral or equivalent level, which are usually provided by universities)",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "mt37cOH28F9",
  //   displayName: "HHM_1 - Place of delivery",
  //   displayFormName:
  //     "Place of delivery (for live birth or stillbirth last year):",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "Health facility",
  //       label: "Health facility",
  //     },
  //     {
  //       value: "Home (attended by skilled healthcare provider)",
  //       label: "Home (attended by skilled healthcare provider)",
  //     },
  //     {
  //       value: "Home (Not attended by skilled healthcare provider)",
  //       label: "Home (Not attended by skilled healthcare provider)",
  //     },
  //     {
  //       value: "Others (attended by skilled healthcare provider)",
  //       label: "Others (attended by skilled healthcare provider)",
  //     },
  //     {
  //       value: "Others (not attended by skilled healthcare provider)",
  //       label: "Others (not attended by skilled healthcare provider)",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "uQg4s7Jd8WW",
  //   displayName: "HHM_1 - Place of incidence",
  //   displayFormName: "Place of incidence",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "Health facility",
  //       label: "Health facility",
  //     },
  //     {
  //       value: "Home (attended by skilled healthcare provider)",
  //       label: "Home (attended by skilled healthcare provider)",
  //     },
  //     {
  //       value: "Home (Not attended by skilled healthcare provider)",
  //       label: "Home (Not attended by skilled healthcare provider)",
  //     },
  //     {
  //       value: "Others (attended by skilled healthcare provider)",
  //       label: "Others (attended by skilled healthcare provider)",
  //     },
  //     {
  //       value: "Others (not attended by skilled healthcare provider)",
  //       label: "Others (not attended by skilled healthcare provider)",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "Fr5ML76aJNF",
  //   displayName: "HHM_1 - Pregnant/Giving birth/42 days of pregnancy",
  //   displayFormName:
  //     "Was she pregnant, giving birth or within 42 days of pregnancy outcome",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "Yes",
  //       label: "Yes",
  //     },
  //     {
  //       value: "No",
  //       label: "No",
  //     },
  //     {
  //       value: "N/A",
  //       label: "N/A",
  //     },
  //     {
  //       value: "Don't know",
  //       label: "Don't know",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "pyzd5HgSFPb",
  //   displayName: "HHM_1 - Recent H. pylori test",
  //   displayFormName:
  //     "When was his/her most recent test for H. pylori infection? (Specify year)",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "zxllKSJ52U1",
  //   displayName: "HHM_1 - Stillbirth last year",
  //   displayFormName: "Number of stillbirth last year:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "CMyXmIIL2Pg",
  //   displayName: "HHM_1 - Systolic (mmHg)_1",
  //   displayFormName: "Systolic (mmHg)",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ZwfMynjw1Ys",
  //   displayName: "HHM_1 - Systolic (mmHg)_2",
  //   displayFormName: "Systolic (mmHg)",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "wEWyO97SUBc",
  //   displayName: "HHM_1 - Systolic (mmHg)_3",
  //   displayFormName: "Systolic (mmHg)",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "D8IeOPkU4dF",
  //   displayName: "HHM_1 - Tested for cervical cancer",
  //   displayFormName:
  //     "Has a doctor or other healthcare worker ever tested her for cervical cancer",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "F6ed0skrJQw",
  //   displayName: "HHM_1 - Transferred to",
  //   displayFormName: "Transferred to",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "In country",
  //       label: "In country",
  //     },
  //     {
  //       value: "Ex country",
  //       label: "Ex country",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "vWP61ahAkEn",
  //   displayName:
  //     "HHM_1 - Treatment recieved for blood pressure in last 2 weeks",
  //   displayFormName:
  //     "During the past two weeks, have you been treated for raised blood pressure with drugs (medication) prescribed by a doctor or other health worker?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ZbunNrGNEx7",
  //   displayName: "HHM_1 - Using hearing aid",
  //   displayFormName: "use a hearing aid?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "zh9y01mPiMD",
  //   displayName: "HHM_1 - Usual activity during the last 6 months?",
  //   displayFormName: "Usual activity during the last 6 months?",
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value:
  //         "Working (including Subsistence Farmers, Religious Professionals, unpaid workers and business)",
  //       label:
  //         "Working (including Subsistence Farmers, Religious Professionals, unpaid workers and business)",
  //     },
  //     {
  //       value: "Doing household chores",
  //       label: "Doing household chores",
  //     },
  //     {
  //       value: "Student",
  //       label: "Student",
  //     },
  //     {
  //       value: "Retired",
  //       label: "Retired",
  //     },
  //     {
  //       value: "Doing nothing",
  //       label: "Doing nothing",
  //     },
  //   ],
  // },
  // {
  //   compulsory: false,
  //   id: "nxzNOl3Qjwc",
  //   displayName: "HHM_1 - Latest cervical cancer test year",
  //   displayFormName:
  //     "When was her most recent test for cervical cancer (Specify year)",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "R64k3NNm72d",
  //   displayName: "HHM_1 - Tested for breast cancer",
  //   displayFormName:
  //     "Has a doctor or other healthcare worker ever examined her breasts to check for breast cancer?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ig2YSpQdP55",
  //   displayName: "MD Family UID",
  //   displayFormName: "Family UID",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "zbQG9VzXEwQ",
  //   displayName: "HHM_2 - 10 mins cycling",
  //   displayFormName:
  //     "In a typical week, on how many days do you do vigorous- intensity activities as part of your work? Number of days:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ytkIZFQcene",
  //   displayName: "HHM_2 - Age when started smoking",
  //   displayFormName: "How old were you when you first started smoking? Years:",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "dmBGs4QGUbu",
  //   displayName: "HHM_2 - alcohol consumption",
  //   displayFormName:
  //     "During the past three months, how often have you had a strong desire or urge to consume areca nut or its products?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "Y68nILE3Hbm",
  //   displayName: "HHM_2 - alcohol consumption-12 months",
  //   displayFormName:
  //     "During the past three months, how often have you failed to do what was normally expected of you because of you consuming areca nut or its products?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "xOAkG4s0XYb",
  //   displayName: "HHM_2 - alcohol consumption - failing responsibilities",
  //   displayFormName:
  //     "How old were you when you first started consuming alcohol? Years:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "Y8Y097LoIrP",
  //   displayName: "HHM_2 - alcohol consumption frequency",
  //   displayFormName:
  //     "Has a friend or relative or anyone else ever expressed concern about you consuming areca nut or its products?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "Tb38VQldkEr",
  //   displayName: "HHM_2 - Areca nut consumption",
  //   displayFormName:
  //     "During the past three months, how often has using smokeless tobacco products led to health, social, legal or financial problems?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "I064ESZkgag",
  //   displayName: "HHM_2 - areca nut consumption - failing responsibilities",
  //   displayFormName:
  //     "Have you ever consumed areca nut or its products (Doma, Paan, Supari, etc)?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ZcfMOSb2YAW",
  //   displayName: "HHM_2 - areca nut consumption frequency",
  //   displayFormName:
  //     "Have you ever tried to cut down on using smokeless tobacco products but failed?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "eWjobHqRmVR",
  //   displayName: "HHM_2 - Asprin consumption",
  //   displayFormName: "Were you first told in the past 12 months?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "hWWA6W6Vvgf",
  //   displayName: "HHM_2 - Blood pressure measured by doctor",
  //   displayFormName:
  //     "In a typical week, on how many days do you do vigorous- intensity sports, fitness or recreational (leisure) activities? Number of days:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "cMd8GGJgTLT",
  //   displayName: "HHM_2 - Blood sugar measured",
  //   displayFormName:
  //     "Have you ever been told by a doctor or other health worker that you have raised blood pressure or hypertension?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "Oi1PtLq78V8",
  //   displayName: "HHM_2 - BP traditional remedies",
  //   displayFormName:
  //     "Have you ever had your blood pressure measured by a doctor or other health worker?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "gKEcTk9bVeg",
  //   displayName: "HHM_2 - Cholesterol local treatment",
  //   displayFormName:
  //     "Have you ever had your cholesterol (fat levels in your blood) measured by a doctor or other health worker?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "N3aQ8FrbXga",
  //   displayName: "HHM_2 - Cholesterol measured by doctor",
  //   displayFormName:
  //     "Have you ever received an eye examination after you were told by a doctor or other health worker that you have raised blood sugar or diabetes?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "j8vPhrQ93Ye",
  //   displayName: "HHM_2 - Cholesterol medication by doctor",
  //   displayFormName:
  //     "Have you ever seen a local healer like Tsip/ Jhakri/ Neyjom/ Lama/ Pow for diabetes or raised blood sugar?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "XbokNSO2zVH",
  //   displayName: "HHM_2 - Concern about alcohol consumption",
  //   displayFormName:
  //     "In the past three months, how often have you consumed alcohol?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "x4Vn8TFDtol",
  //   displayName: "HHM_2 - Concern about areca nut consumption",
  //   displayFormName:
  //     "How old were you when you first started consuming areca nut or its products?",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "gVbtSt6UaCK",
  //   displayName: "HHM_2 - Concern about smoking",
  //   displayFormName:
  //     "Was she pregnant, giving birth or within 42 days of pregnancy outcome",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "v6h7EhZw5Ui",
  //   displayName: "HHM_2 - daily cycling",
  //   displayFormName:
  //     "Does your work involve moderate-intensity activity that causes small increases in breathing or heart rate such as brisk walking [or carrying light loads, mopping or sweeping floors or dance] for at least 10 minutes continuously?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "rhOQjp901FX",
  //   displayName: "HHM_2 - daily exertion",
  //   displayFormName:
  //     "Does your work involve vigorous-intensity activity that causes large increases in breathing or heart rate like [carrying or lifting heavy loads, heavy digging or construction work, chopping woods with axe, cham dance] for at least",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "NAZ7d8bUbjd",
  //   displayName: "HHM_2 - Daily physical exertion work",
  //   displayFormName:
  //     "How many servings of fruit do you eat on one of those days? Number of servings:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ZLQF5qBLWlQ",
  //   displayName: "HHM_2 - Daily sports",
  //   displayFormName:
  //     "Do you walk or use a bicycle (pedal cycle) for at least 10 minutes continuously to get to and from places?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "t90UIe4vFSX",
  //   displayName: "HHM_2 - Daily - Sports - moderate intensity",
  //   displayFormName:
  //     "Do you do any vigorous-intensity sports, fitness or recreational (leisure) activities that cause large increases in breathing or heart rate like [running or football or basketball, volleyball, badminton, skipping, keshey ect.] for",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "kb8mwrpjGGU",
  //   displayName: "HHM_2 - Desire for alcohol consumption",
  //   displayFormName:
  //     "Have you ever tried to cut down on consuming areca nut or its productsbut failed?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "nZgJU0CKihb",
  //   displayName: "HHM_2 - Desire for areca nut consumption",
  //   displayFormName: "Waist circumference (cm):",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "NJYj8K15jBK",
  //   displayName: "HHM_2 - Desire to smoke",
  //   displayFormName: "If Accidental",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ZTjoxxpLJRt",
  //   displayName: "HHM_2 - Desire to tobacco products",
  //   displayFormName:
  //     "Has a friend or relative or anyone else ever expressed concern about your smoking habit?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "QY3jBX7waUm",
  //   displayName: "HHM_2 - Diabetes diagnosed by doctor",
  //   displayFormName: "Were you first told in the past 12 months?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "yi3wYvQ9aAt",
  //   displayName: "HHM_2 - Diabetes diagnosis in last year",
  //   displayFormName:
  //     "In the past two weeks, have you taken any drugs (medication) for raised blood pressure prescribed by a doctor or other health worker?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "MY7X9t0l8r3",
  //   displayName: "HHM_2 - Diabetes traditional medication",
  //   displayFormName: "Were you first told the past 12 months?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "UkChrCwAdnm",
  //   displayName: "HHM_2 - Drugs prescribed for diabetes",
  //   displayFormName:
  //     "Are you currently taking any herbal or traditional remedy for your raised blood pressure?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "n5n0yLyVwuA",
  //   displayName: "HHM_2 - Eye check up after diabetes diagnosis",
  //   displayFormName:
  //     "Have you ever seen a local healer like Tsip/ Jhakri/ Neyjom/ Lama/ Pow for raised blood pressure or hypertension?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "LRWUTlsJIQP",
  //   displayName: "HHM_2 - Failed alcohol consumption cut down",
  //   displayFormName:
  //     "During the past three months, how often have you had a strong desire or urge to consume alcohol?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "TC0ysGa0ji0",
  //   displayName: "HHM_2 - Failed areca nut consumption cut down",
  //   displayFormName:
  //     "In the past three months, how often have you consumed areca nut or its products?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "w4zA0GSrnY2",
  //   displayName: "HHM_2 - Failed smoking cut down",
  //   displayFormName: "In the past three months, how often have you smoked?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "TT3KCBECRUZ",
  //   displayName: "HHM_2 - Failed tobacco products cut down",
  //   displayFormName:
  //     "How old were you when you first started using smokeless tobacco products? Years:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "Z1AIOXyZEdo",
  //   displayName: "HHM_2 - First started alcohol consumption age",
  //   displayFormName:
  //     "During the past three months, how often has consuming areca nut or its products led to health, social, legal or financial problems?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "WgCarY7Ko0w",
  //   displayName: "HHM_2 - First started areca nut consumption age",
  //   displayFormName:
  //     "During the past three months, how often have you failed to do what was normally expected of you because of you using smokeless tobacco products?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "DlZeFlKCRGr",
  //   displayName: "HHM_2 - First started tobacco products age",
  //   displayFormName:
  //     "During the past three months, how often has your smoking led to health, social, legal or financial problems?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "Di8AmkzbgVG",
  //   displayName: "HHM_2 - Fruit servings",
  //   displayFormName:
  //     "During the past three months, how often have you failed to do what was normally expected of you because of you consuming alcohol?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "PBDkdqR3yWo",
  //   displayName: "HHM_2 - Heart attack, stroke, chest pain",
  //   displayFormName:
  //     "Have you ever been told by a doctor or other health worker that you have raised cholesterol?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "pxqEppI9NuY",
  //   displayName: "HHM_2 - Height in Centimeters(cm)",
  //   displayFormName:
  //     "Are you currently taking any herbal or traditional remedy for your raised cholesterol?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "DBKh0M3rsKO",
  //   displayName: "HHM_2 - Hip circumference (cm)",
  //   displayFormName:
  //     "Are you currently taking aspirin regularly to prevent or treat heart disease?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "k0xgunv5thB",
  //   displayName: "HHM_2 - Hypertention diagnosis by doctor",
  //   displayFormName:
  //     "How much time do you spend doing vigorous-intensity sports, fitness or recreational activities on a typical day? Mins:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "RlTylqBRM17",
  //   displayName: "HHM_2 - Hypertention diagnosis by doctor last year",
  //   displayFormName:
  //     "Do you do any moderate-intensity sports, fitness or recreational (leisure) activities that cause a small increase in breathing or heart rate such as brisk walking, [cycling, gardening, Frisbee, hulahoop, prostrations, dancing, sho",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "vxYznE6Y6NX",
  //   displayName: "HHM_2 - Intense sports",
  //   displayFormName:
  //     "In a typical week, on how many days do you do moderate-intensity activities as part of your work. Number of days:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "lQZCEKfKrvx",
  //   displayName: "HHM_2 - Local healer consulted for BP",
  //   displayFormName:
  //     "How much time do you spend doing moderate-intensity sports, fitness or recreational (leisure) activities on a typical day? Mins: ",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "aUFofe87M5z",
  //   displayName: "HHM_2 - Local healer consulted for cholesterol",
  //   displayFormName:
  //     "Are you currently taking any herbal or traditional remedy for your diabetes?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ywmbicYTIhw",
  //   displayName: "HHM_2 - Local healer consulted for diabetes",
  //   displayFormName:
  //     "Have you ever been told by a doctor or other health worker that you have raised blood sugar or diabetes?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "T5ph3cF6LtQ",
  //   displayName: "HHM_2 - Moderate exertion",
  //   displayFormName:
  //     "In a typical week, on how many days do you eat vegetables? Number of days:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "AMuk90nUTfs",
  //   displayName: "HHM_2 - NCD module individual",
  //   displayFormName: "Is this individual selected for the NCD Module?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "iWaeCiMpBV9",
  //   displayName: "HHM_2 - Pregnant",
  //   displayFormName:
  //     "Have you ever seen a local healer for raised cholesterol?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "S185gnI1Jyq",
  //   displayName: "HHM_2 - Prescribed insulin",
  //   displayFormName:
  //     "Have you ever had your blood sugar (Diabetes) measured by a doctor or other health worker?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ow3jWPZceeS",
  //   displayName: "HHM_2 - Prescribed medication for BP taken",
  //   displayFormName:
  //     "In a typical week, on how many days do you do moderate-intensity sports, fitness or recreational (leisure) activities? Number of days:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "IWmyyzSPchd",
  //   displayName: "HHM_2 - Problems due to alcohol consumption",
  //   displayFormName:
  //     "Have you ever consumed any alcohol such as beer, wine, hard drinks, ara, changkoe, bangchang, shingchang etc?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "vQUMCUTDtzn",
  //   displayName: "HHM_2 - Problems due to areca nut consumption",
  //   displayFormName:
  //     "During the past 30 days, did someone smoke in closed areas in your workplace (in the building, in a work area or specific office)",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "UzYD7jqOBqp",
  //   displayName: "HHM_2 - Problems due to smoking",
  //   displayFormName: "Was the death alcohol related?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "KJ05f4WOeCO",
  //   displayName: "HHM_2 - Problems due to tobacco products",
  //   displayFormName: "Have you ever tried to cut down on smoking but failed?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "TBo8Lw8Rfis",
  //   displayName: "HHM_2 - Raised cholesterol warning",
  //   displayFormName:
  //     "In the past two weeks, have you taken any drugs (medication) for diabetes prescribed by a doctor or other health worker?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "OJaXOHWDGwU",
  //   displayName: "HHM_2 - Raised cholesterol warning last year",
  //   displayFormName:
  //     "Are you currently taking insulin for diabetes prescribed by a doctor or other health worker?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "A4cdhctkNzu",
  //   displayName: "HHM_2 - six or more standard drinks",
  //   displayFormName: "Have you consumed any alcohol within the past 12 months?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "JYX7fyIMwrh",
  //   displayName: "HHM_2 - Smoked tobacco products",
  //   displayFormName:
  //     "Have you ever smoked any tobacco products, such as cigarettes, bidi, cigars or pipes, vape or e-cigarettes?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "l9A9zUdal3y",
  //   displayName: "HHM_2 - Smoking - failing responsibilities",
  //   displayFormName: "Where did he/she pass away?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "PsY5SWSq583",
  //   displayName: "HHM_2 - Smoking frequency",
  //   displayFormName: "Manner of Death",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "qaBIOjngXpL",
  //   displayName: "HHM_2 - Smoking in closed areas",
  //   displayFormName:
  //     "During the past three months, how often have you had a strong desire or urge to use smokeless tobacco products?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "vuQ97rrVTZH",
  //   displayName: "HHM_2 - Sports - moderate intensity",
  //   displayFormName:
  //     "In a typical week, on how many days do you walk or bicycle for at least 10 minutes continuously to get to and from places? Number of days:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "En7TKezqhAz",
  //   displayName: "HHM_2 - Stanins consumption",
  //   displayFormName:
  //     "In the past two weeks, have you taken any oral treatment (medication) for raised total cholesterol prescribed by a doctor or other health worker?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "pul07TNK7nX",
  //   displayName: "HHM_2 - Tobacco products",
  //   displayFormName:
  //     "During the past three months, how often have you had a strong desire or urge to smoke?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "EKGSw9xQZSC",
  //   displayName: "HHM_2 - tobacco products - failing responsibilities",
  //   displayFormName:
  //     "Have you ever used any smokeless tobacco products such as [snuff, chewing tobacco, betel quid with tobacco]?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "fhcVXetFGxn",
  //   displayName: "HHM_2 - tobacco products frequency",
  //   displayFormName:
  //     "During the past three months, how often have you failed to do what was normally expected of you because of your smoking habit?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "Nt3mxnRg81J",
  //   displayName: "HHM_2 - Vegetable serving",
  //   displayFormName:
  //     "Has a friend or relative or anyone else ever expressed concern about you consuming alcohol?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "KfRuikfQldK",
  //   displayName: "HHM_2 - Waist circumference (cm)",
  //   displayFormName:
  //     "In the past three months, how often have you used smokeless tobacco products?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "x4rAVIrHNQW",
  //   displayName: "HHM_2 - weekly cycling",
  //   displayFormName:
  //     "How much time do you spend doing vigorous-intensity activities at work on a typical day? Mins:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "RoH08osPgJe",
  //   displayName: "HHM_2 - weekly exertion",
  //   displayFormName:
  //     "How many servings of vegetables do you eat on one of those days? Number of servings:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "qys7jQQ8Ecs",
  //   displayName: "HHM_2 - Weekly fruit consumption",
  //   displayFormName:
  //     "During the past three months, how often has consuming alcohol led to health, social, legal or financial problems?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "I09jWdGQDsn",
  //   displayName: "HHM_2 - weekly physical exertion work",
  //   displayFormName:
  //     "In a typical week, on how many days do you eat fruit? Number of days:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "egLB4q5WL2n",
  //   displayName: "HHM_2 - Weekly sports",
  //   displayFormName:
  //     "How much time do you spend doing moderate-intensity activities at work on a typical day? Mins:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "ckV0yOEytlG",
  //   displayName: "HHM_2 - Weekly - Sports - moderate intensity",
  //   displayFormName:
  //     "How much time do you spend walking or bicycling for travel on a typical day? Mins:",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "xl2mqLHkDff",
  //   displayName: "HHM_2 - Weekly vegetable consumption",
  //   displayFormName:
  //     "During the past 30 days, how many times did you have six or more standard drinks in a single drinking occasion?",
  //   valueType: "NUMBER",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "CszAgcZlA2I",
  //   displayName: "HHM_2 - Weight in Kilogram(kg)",
  //   displayFormName:
  //     "Have you ever had a heart attack or chest pain from heart disease (angina) or a stroke (cerebrovascular accident or incident)?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "kEL5hSBu6gC",
  //   displayName: "HHM_2 - Work related physical exertion",
  //   displayFormName:
  //     "Have you ever tried to cut down on consuming aalcohol but failed?",
  //   valueType: "TEXT",
  //   valueSet: null,
  // },
  // {
  //   compulsory: false,
  //   id: "KLQOqxBSInZ",
  //   displayName: "HHM_2 - Smoking in home",
  //   displayFormName: "During the past 30 days, did someone smoke in your home?",
  //   valueType: "BOOLEAN",
  //   valueSet: null,
  // },
];

const originMetadata1 = [
  // {
  //   name: "Family member details 4.0 ID type",
  //   created: "2024-11-20T13:43:38.194",
  //   lastUpdated: "2024-11-20T14:42:36.510",
  //   translations: [],
  //   program: {
  //     id: "xvzrp56zKvI",
  //   },
  //   displayInList: true,
  //   sortOrder: 1,
  //   mandatory: false,
  //   renderOptionsAsRadio: false,
  //   searchable: false,
  //   valueType: "TEXT",
  //   displayShortName: "Family member details 4.0 ID type",
  //   displayName: "Family member details 4.0 ID type",
  //   favorite: false,
  //   id: "dZ2Z2FrRPDe",
  //   attributeValues: [],
  //   trackedEntityAttribute: {
  //     formName: "ID type",
  //     valueType: "TEXT",
  //     unique: false,
  //     pattern: "",
  //     displayName: "ID type",
  //     displayShortName: "ID type",
  //     displayFormName: "ID type",
  //     optionSetValue: true,
  //     valueSet: {
  //       code: "ID type",
  //       name: "ID type",
  //       translations: [],
  //       options: [
  //         {
  //           code: "CID",
  //           name: "CID",
  //           translations: [],
  //           sortOrder: 1,
  //           id: "rZnpbviBJaQ",
  //           attributeValues: [],
  //         },
  //         {
  //           code: "Green Card Holder",
  //           name: "Green Card Holder",
  //           translations: [],
  //           sortOrder: 2,
  //           id: "scrvACi39ri",
  //           attributeValues: [],
  //         },
  //         {
  //           code: "Marriage Certificate",
  //           name: "Marriage Certificate",
  //           translations: [],
  //           sortOrder: 3,
  //           id: "lwTNKchleKI",
  //           attributeValues: [],
  //         },
  //         {
  //           code: "MCH no.",
  //           name: "MCH no.",
  //           translations: [],
  //           sortOrder: 4,
  //           id: "o7eijaTDz00",
  //           attributeValues: [],
  //         },
  //         {
  //           code: "Passport",
  //           name: "Passport",
  //           translations: [],
  //           sortOrder: 5,
  //           id: "LD3nfO4U6QJ",
  //           attributeValues: [],
  //         },
  //       ],
  //       id: "noSWgaRUarU",
  //       attributeValues: [],
  //     },
  //     id: "CADfVSQEVVi",
  //     attributeValues: [],
  //   },
  // },
  // {
  //   name: "Family member details 4.0 Country ID",
  //   created: "2024-11-20T13:43:38.194",
  //   lastUpdated: "2024-11-20T14:42:36.511",
  //   translations: [],
  //   externalAccess: false,
  //   userGroupAccesses: [],
  //   userAccesses: [],
  //   favorites: [],
  //   program: {
  //     id: "xvzrp56zKvI",
  //   },
  //   displayInList: true,
  //   sortOrder: 2,
  //   mandatory: false,
  //   renderOptionsAsRadio: false,
  //   searchable: false,
  //   valueType: "TEXT",
  //   displayShortName: "Family member details 4.0 Country ID",
  //   displayName: "Family member details 4.0 Country ID",
  //   favorite: false,
  //   id: "KONEkGFTb2s",
  //   attributeValues: [],
  //   trackedEntityAttribute: {
  //     formName: "Country ID",
  //     valueType: "TEXT",
  //     unique: false,
  //     pattern: "",
  //     displayName: "Country ID",
  //     displayShortName: "Country ID",
  //     displayFormName: "Country ID",
  //     optionSetValue: false,
  //     id: "rOA2ACbkXug",
  //     attributeValues: [],
  //   },
  // },
  // {
  //   name: "Family member details 4.0 UHID",
  //   created: "2024-11-20T13:43:38.194",
  //   lastUpdated: "2024-11-20T14:42:36.511",
  //   translations: [],
  //   externalAccess: false,
  //   userGroupAccesses: [],
  //   userAccesses: [],
  //   favorites: [],
  //   program: {
  //     id: "xvzrp56zKvI",
  //   },
  //   displayInList: true,
  //   sortOrder: 3,
  //   mandatory: false,
  //   renderOptionsAsRadio: false,
  //   searchable: false,
  //   valueType: "TEXT",
  //   displayShortName: "Family member details 4.0 UHID",
  //   displayName: "Family member details 4.0 UHID",
  //   favorite: false,
  //   id: "KAmyo4tnJGp",
  //   attributeValues: [],
  //   trackedEntityAttribute: {
  //     formName: "UHID",
  //     valueType: "TEXT",
  //     unique: false,
  //     pattern: "",
  //     displayName: "UHID",
  //     displayShortName: "UHID",
  //     displayFormName: "UHID",
  //     optionSetValue: false,
  //     id: "vrM7vt4JZmQ",
  //     attributeValues: [],
  //   },
  // },
  // {
  //   name: "Family member details 4.0 Name",
  //   created: "2024-11-20T13:43:38.194",
  //   lastUpdated: "2024-11-20T14:42:36.511",
  //   translations: [],
  //   externalAccess: false,
  //   userGroupAccesses: [],
  //   userAccesses: [],
  //   favorites: [],
  //   program: {
  //     id: "xvzrp56zKvI",
  //   },
  //   displayInList: true,
  //   sortOrder: 4,
  //   mandatory: false,
  //   renderOptionsAsRadio: false,
  //   searchable: false,
  //   valueType: "TEXT",
  //   displayShortName: "Family member details 4.0 Name",
  //   displayName: "Family member details 4.0 Name",
  //   favorite: false,
  //   id: "NsZx5rdbGRS",
  //   attributeValues: [],
  //   trackedEntityAttribute: {
  //     formName: "Name",
  //     valueType: "TEXT",
  //     unique: false,
  //     pattern: "",
  //     displayName: "Name",
  //     displayShortName: "Name",
  //     displayFormName: "Name",
  //     optionSetValue: false,
  //     id: "s7f3ayF0MEG",
  //     attributeValues: [],
  //   },
  // },
  // {
  //   name: "Family member details 4.0 Date of birth",
  //   created: "2024-11-20T13:43:38.194",
  //   lastUpdated: "2024-11-20T14:42:36.511",
  //   translations: [],
  //   externalAccess: false,
  //   userGroupAccesses: [],
  //   userAccesses: [],
  //   favorites: [],
  //   program: {
  //     id: "xvzrp56zKvI",
  //   },
  //   displayInList: true,
  //   sortOrder: 5,
  //   mandatory: false,
  //   renderOptionsAsRadio: false,
  //   searchable: false,
  //   valueType: "AGE",
  //   displayShortName: "Family member details 4.0 Date of birth",
  //   displayName: "Family member details 4.0 Date of birth",
  //   favorite: false,
  //   id: "KGekkAOjdhw",
  //   attributeValues: [],
  //   trackedEntityAttribute: {
  //     formName: "Date of birth",
  //     valueType: "AGE",
  //     unique: false,
  //     pattern: "",
  //     displayName: "Date of birth",
  //     displayShortName: "Date of birth",
  //     displayFormName: "Date of birth",
  //     optionSetValue: false,
  //     id: "rB3psCPmxwE",
  //     attributeValues: [],
  //   },
  // },
  // {
  //   name: "Family member details 4.0 Sex",
  //   created: "2024-11-20T13:43:38.194",
  //   lastUpdated: "2024-11-20T14:42:36.511",
  //   translations: [],
  //   externalAccess: false,
  //   userGroupAccesses: [],
  //   userAccesses: [],
  //   favorites: [],
  //   program: {
  //     id: "xvzrp56zKvI",
  //   },
  //   displayInList: true,
  //   sortOrder: 6,
  //   mandatory: false,
  //   renderOptionsAsRadio: false,
  //   searchable: false,
  //   valueType: "TEXT",
  //   displayShortName: "Family member details 4.0 Sex",
  //   displayName: "Family member details 4.0 Sex",
  //   favorite: false,
  //   id: "Fwsx794LLqX",
  //   attributeValues: [],
  //   trackedEntityAttribute: {
  //     formName: "Sex",
  //     valueType: "TEXT",
  //     valueSet: {
  //       code: "Sex",
  //       name: "Sex",
  //       translations: [],
  //       options: [
  //         {
  //           code: "Male",
  //           name: "Male",
  //           translations: [],
  //           sortOrder: 1,
  //           id: "NAfA68NCVFh",
  //           attributeValues: [],
  //         },
  //         {
  //           code: "Female",
  //           name: "Female",
  //           translations: [],
  //           sortOrder: 2,
  //           id: "QehEFc5wV5T",
  //           attributeValues: [],
  //         },
  //       ],
  //       id: "rD9ZqOfGgaS",
  //       attributeValues: [],
  //     },
  //     unique: false,
  //     pattern: "",
  //     displayName: "Sex",
  //     displayShortName: "Sex",
  //     displayFormName: "Sex",
  //     optionSetValue: true,
  //     id: "MYaNKVVYIQT",
  //     attributeValues: [],
  //   },
  // },
  // {
  //   name: "Family member details 4.0 Contact Number",
  //   created: "2024-11-20T13:43:38.194",
  //   lastUpdated: "2024-11-20T14:42:36.511",
  //   translations: [],
  //   externalAccess: false,
  //   userGroupAccesses: [],
  //   userAccesses: [],
  //   favorites: [],
  //   program: {
  //     id: "xvzrp56zKvI",
  //   },
  //   displayInList: true,
  //   sortOrder: 7,
  //   mandatory: false,
  //   renderOptionsAsRadio: false,
  //   searchable: false,
  //   valueType: "NUMBER",
  //   displayShortName: "Family member details 4.0 Contact Number",
  //   displayName: "Family member details 4.0 Contact Number",
  //   favorite: false,
  //   id: "c8Lgoc3vNJi",
  //   attributeValues: [],
  //   trackedEntityAttribute: {
  //     formName: "Contact Number",
  //     valueType: "NUMBER",
  //     unique: false,
  //     pattern: "",
  //     displayName: "Contact Number",
  //     displayShortName: "Contact Number",
  //     displayFormName: "Contact Number",
  //     optionSetValue: false,
  //     id: "HyGJqEzbxD4",
  //     attributeValues: [],
  //   },
  // },
  // {
  //   name: "Family member details 4.0 Unique dwelling ID",
  //   created: "2024-11-20T13:43:38.194",
  //   lastUpdated: "2024-11-20T14:42:36.511",
  //   translations: [],
  //   externalAccess: false,
  //   userGroupAccesses: [],
  //   userAccesses: [],
  //   favorites: [],
  //   program: {
  //     id: "xvzrp56zKvI",
  //   },
  //   displayInList: true,
  //   sortOrder: 8,
  //   mandatory: false,
  //   renderOptionsAsRadio: false,
  //   searchable: false,
  //   valueType: "TEXT",
  //   displayShortName: "Family member details 4.0 Unique dwelling ID",
  //   displayName: "Family member details 4.0 Unique dwelling ID",
  //   favorite: false,
  //   id: "ix7lkPzs6XM",
  //   attributeValues: [],
  //   trackedEntityAttribute: {
  //     formName: "Unique dwelling ID",
  //     valueType: "TEXT",
  //     unique: false,
  //     pattern: "",
  //     displayName: "Unique dwelling ID",
  //     displayShortName: "Unique dwelling ID",
  //     displayFormName: "Unique dwelling ID",
  //     optionSetValue: false,
  //     id: "hDE1WNqTTwF",
  //     attributeValues: [],
  //   },
  // },
  // {
  //   dataElement: {
  //     valueType: "TEXT",
  //     valueSet: {
  //       code: "Membership Status",
  //       name: "Membership Status",
  //       translations: [],
  //       options: [
  //         {
  //           code: "Present",
  //           name: "Present",
  //           translations: [],
  //           displayName: "Present",
  //           id: "jIFpYXSw3Gt",
  //           attributeValues: [],
  //         },
  //         {
  //           code: "Demise",
  //           name: "Demise",
  //           translations: [],
  //           displayName: "Demise",
  //           id: "HCFYJffamov",
  //           attributeValues: [],
  //         },
  //         {
  //           code: "Transferred",
  //           name: "Transferred",
  //           translations: [],
  //           displayName: "Transferred",
  //           id: "rCq4Jte9x3x",
  //           attributeValues: [],
  //         },
  //       ],
  //       valueType: "TEXT",
  //       version: 3,
  //       displayName: "Membership Status",
  //       id: "p1mPcT964KJ",
  //       attributeValues: [],
  //     },
  //     displayName: "HHM_1 - Membership Status",
  //     displayShortName: "HHM_1 - Membership Status",
  //     displayFormName: "Membership Status",
  //     id: "cP1EanFicmA",
  //     attributeValues: [
  //       {
  //         attribute: {
  //           id: "KhGyBaFWXZT",
  //         },
  //         value: "member_form",
  //       },
  //     ],
  //   },
  //   compulsory: false,
  // },
  // {
  //   code: "sex",
  //   name: "Sex",
  //   id: "w1pdC1I8xsh",
  //   disable: false,
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "M",
  //       label: "Male",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Male"],
  //       translations: {
  //         lo: "ຊາຍ",
  //       },
  //     },
  //     {
  //       value: "F",
  //       label: "Female",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Female"],
  //       translations: {
  //         lo: "ຍິງ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ເພດ",
  //     en: "Sex",
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "firstname",
  //   name: "First name",
  //   id: "gvtjbfq41hn",
  //   disable: false,
  //   valueType: "MASK",
  //   pattern: /^\D+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ຊື່",
  //     en: "First name",
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "lastname",
  //   name: "Last name",
  //   id: "xru22thNYm0",
  //   disable: false,
  //   valueType: "MASK",
  //   pattern: /^\D+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ນາມສະກູນ",
  //     en: "Last name",
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "relation",
  //   name: "Relation with head",
  //   id: "feO2931a74k",
  //   disable: false,
  //   valueType: "TEXT",
  //   existCompulsory: true,
  //   valueSet: [
  //     {
  //       value: "head",
  //       label: "Head of family",
  //       isDisabled: false,
  //       compulsory: true,
  //       unique: true,
  //       multiple: ["Head of family"],
  //       translations: {
  //         lo: "ຫົວໜ້າຄອບຄົວ",
  //         vi: "ຫົວໜ້າຄອບຄົວ",
  //       },
  //     },
  //     {
  //       value: "wife",
  //       label: "Wife",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Wife"],
  //       translations: {
  //         lo: "ເມຍ",
  //         vi: "ເມຍ",
  //       },
  //     },
  //     {
  //       value: "children",
  //       label: "Children",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Children"],
  //       translations: {
  //         lo: "ລູກ",
  //         vi: "ລູກ",
  //       },
  //     },
  //     {
  //       value: "relatives",
  //       label: "Other Relatives",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Other Relatives"],
  //       translations: {
  //         lo: "ຍາດພີ່ນ້ອງ",
  //         vi: "ຍາດພີ່ນ້ອງ",
  //       },
  //     },
  //     {
  //       value: "parent",
  //       label: "Parents",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Parents"],
  //       translations: {
  //         lo: "ພໍ່ແມ່",
  //         vi: "ພໍ່ແມ່",
  //       },
  //     },
  //     {
  //       value: "others",
  //       label: "Others",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Others"],
  //       translations: {
  //         lo: "ອື່ນໆ",
  //         vi: "ອື່ນໆ",
  //       },
  //     },
  //   ],
  //   sort: "true",
  //   translations: {
  //     lo: "ສາຍພົວພັນກັບຫົວໜ້າຄອບຄົວ",
  //     en: "Relation with head",
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "ethnicity",
  //   name: "Ethnicity",
  //   id: "xee9ddPU5eI",
  //   disable: false,
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "ລາວ",
  //       label: "Lao",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ລາວ"],
  //       translations: {
  //         lo: "ລາວ",
  //       },
  //     },
  //     {
  //       value: "ໄຕ",
  //       label: "Tai",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ໄຕ"],
  //       translations: {
  //         lo: "ໄຕ",
  //       },
  //     },
  //     {
  //       value: "ຜູ້ໄທ",
  //       label: "Phouthai",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຜູ້ໄທ"],
  //       translations: {
  //         lo: "ຜູ້ໄທ",
  //       },
  //     },
  //     {
  //       value: "ລື້",
  //       label: "Lue",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ລື້"],
  //       translations: {
  //         lo: "ລື້",
  //       },
  //     },
  //     {
  //       value: "ຍວນ",
  //       label: "Nyouan",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຍວນ"],
  //       translations: {
  //         lo: "ຍວນ",
  //       },
  //     },
  //     {
  //       value: "ຢັ້ງ",
  //       label: "Nyung",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຢັ້ງ"],
  //       translations: {
  //         lo: "ຢັ້ງ",
  //       },
  //     },
  //     {
  //       value: "ແຊກ",
  //       label: "Xek",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ແຊກ"],
  //       translations: {
  //         lo: "ແຊກ",
  //       },
  //     },
  //     {
  //       value: "ໄທເໜືອ",
  //       label: "Thai-nua",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ໄທເໜືອ"],
  //       translations: {
  //         lo: "ໄທເໜືອ",
  //       },
  //     },
  //     {
  //       value: "ກຶມມຸ",
  //       label: "Khmou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ກຶມມຸ"],
  //       translations: {
  //         lo: "ກຶມມຸ",
  //       },
  //     },
  //     {
  //       value: "ໄປຣ",
  //       label: "Prai",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ໄປຣ"],
  //       translations: {
  //         lo: "ໄປຣ",
  //       },
  //     },
  //     {
  //       value: "ຊິງມູນ",
  //       label: "Xingmoun",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຊິງມູນ"],
  //       translations: {
  //         lo: "ຊິງມູນ",
  //       },
  //     },
  //     {
  //       value: "ຜ້ອງ",
  //       label: "Phong",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຜ້ອງ"],
  //       translations: {
  //         lo: "ຜ້ອງ",
  //       },
  //     },
  //     {
  //       value: "ແທ່ນ",
  //       label: "Then",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ແທ່ນ"],
  //       translations: {
  //         lo: "ແທ່ນ",
  //       },
  //     },
  //     {
  //       value: "ເອີດູ",
  //       label: "Oeu-dou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ເອີດູ"],
  //       translations: {
  //         lo: "ເອີດູ",
  //       },
  //     },
  //     {
  //       value: "ບິດ",
  //       label: "Bid",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ບິດ"],
  //       translations: {
  //         lo: "ບິດ",
  //       },
  //     },
  //     {
  //       value: "ລະເມດ",
  //       label: "Lamed",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ລະເມດ"],
  //       translations: {
  //         lo: "ລະເມດ",
  //       },
  //     },
  //     {
  //       value: "ສາມຕ່າວ",
  //       label: "Samtao",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ສາມຕ່າວ"],
  //       translations: {
  //         lo: "ສາມຕ່າວ",
  //       },
  //     },
  //     {
  //       value: "ກະຕ່າງ",
  //       label: "Ka-tang",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ກະຕ່າງ"],
  //       translations: {
  //         lo: "ກະຕ່າງ",
  //       },
  //     },
  //     {
  //       value: "ມະກອງ",
  //       label: "Makong",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ມະກອງ"],
  //       translations: {
  //         lo: "ມະກອງ",
  //       },
  //     },
  //     {
  //       value: "ຕຣີ",
  //       label: "Tri",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຕຣີ"],
  //       translations: {
  //         lo: "ຕຣີ",
  //       },
  //     },
  //     {
  //       value: "ຢຣຸ",
  //       label: "Nyrou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຢຣຸ"],
  //       translations: {
  //         lo: "ຢຣຸ",
  //       },
  //     },
  //     {
  //       value: "ຕຣຽງ",
  //       label: "Triang",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຕຣຽງ"],
  //       translations: {
  //         lo: "ຕຣຽງ",
  //       },
  //     },
  //     {
  //       value: "ຕະໂອ້ຍ",
  //       label: "Ta-oy",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຕະໂອ້ຍ"],
  //       translations: {
  //         lo: "ຕະໂອ້ຍ",
  //       },
  //     },
  //     {
  //       value: "ແຢະ",
  //       label: "Nyeh",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ແຢະ"],
  //       translations: {
  //         lo: "ແຢະ",
  //       },
  //     },
  //     {
  //       value: "ເບຣົາ",
  //       label: "Brao",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ເບຣົາ"],
  //       translations: {
  //         lo: "ເບຣົາ",
  //       },
  //     },
  //     {
  //       value: "ກະຕູ",
  //       label: "Katou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ກະຕູ"],
  //       translations: {
  //         lo: "ກະຕູ",
  //       },
  //     },
  //     {
  //       value: "ຮາຮັກ",
  //       label: "Harak",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຮາຮັກ"],
  //       translations: {
  //         lo: "ຮາຮັກ",
  //       },
  //     },
  //     {
  //       value: "ໂອຍ",
  //       label: "Oy",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ໂອຍ"],
  //       translations: {
  //         lo: "ໂອຍ",
  //       },
  //     },
  //     {
  //       value: "ກຣຽງ",
  //       label: "Kriang",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ກຣຽງ"],
  //       translations: {
  //         lo: "ກຣຽງ",
  //       },
  //     },
  //     {
  //       value: "ເຈັງ",
  //       label: "Cheng",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ເຈັງ"],
  //       translations: {
  //         lo: "ເຈັງ",
  //       },
  //     },
  //     {
  //       value: "ສະດ່າງ",
  //       label: "Sadang",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ສະດ່າງ"],
  //       translations: {
  //         lo: "ສະດ່າງ",
  //       },
  //     },
  //     {
  //       value: "ຊ່ວຍ",
  //       label: "Xouay",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຊ່ວຍ"],
  //       translations: {
  //         lo: "ຊ່ວຍ",
  //       },
  //     },
  //     {
  //       value: "ຍະເຫີນ",
  //       label: "Nyaheun",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຍະເຫີນ"],
  //       translations: {
  //         lo: "ຍະເຫີນ",
  //       },
  //     },
  //     {
  //       value: "ລະວີ",
  //       label: "Lavi",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ລະວີ"],
  //       translations: {
  //         lo: "ລະວີ",
  //       },
  //     },
  //     {
  //       value: "ປະໂກະ",
  //       label: "Pako",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ປະໂກະ"],
  //       translations: {
  //         lo: "ປະໂກະ",
  //       },
  //     },
  //     {
  //       value: "ຂະແມ່",
  //       label: "Kha-meh",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຂະແມ່"],
  //       translations: {
  //         lo: "ຂະແມ່",
  //       },
  //     },
  //     {
  //       value: "ຕຸ້ມ",
  //       label: "Toum",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຕຸ້ມ"],
  //       translations: {
  //         lo: "ຕຸ້ມ",
  //       },
  //     },
  //     {
  //       value: "ງວນ",
  //       label: "Ngouan",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ງວນ"],
  //       translations: {
  //         lo: "ງວນ",
  //       },
  //     },
  //     {
  //       value: "ມ້ອຍ",
  //       label: "Moy",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ມ້ອຍ"],
  //       translations: {
  //         lo: "ມ້ອຍ",
  //       },
  //     },
  //     {
  //       value: "ກຣີ",
  //       label: "Kri",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ກຣີ"],
  //       translations: {
  //         lo: "ກຣີ",
  //       },
  //     },
  //     {
  //       value: "ມົ້ງ",
  //       label: "Hmong",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ມົ້ງ"],
  //       translations: {
  //         lo: "ມົ້ງ",
  //       },
  //     },
  //     {
  //       value: "ອີວມຽນ",
  //       label: "Eio-miang",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ອີວມຽນ"],
  //       translations: {
  //         lo: "ອີວມຽນ",
  //       },
  //     },
  //     {
  //       value: "ອາຄາ",
  //       label: "Akha",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ອາຄາ"],
  //       translations: {
  //         lo: "ອາຄາ",
  //       },
  //     },
  //     {
  //       value: "ພູນ້ອຍ",
  //       label: "Phou-noy",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ພູນ້ອຍ"],
  //       translations: {
  //         lo: "ພູນ້ອຍ",
  //       },
  //     },
  //     {
  //       value: "ລາຫູ",
  //       label: "Lahou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ລາຫູ"],
  //       translations: {
  //         lo: "ລາຫູ",
  //       },
  //     },
  //     {
  //       value: "ສີລາ",
  //       label: "Sila",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ສີລາ"],
  //       translations: {
  //         lo: "ສີລາ",
  //       },
  //     },
  //     {
  //       value: "ຮາຍີ",
  //       label: "Hayi",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຮາຍີ"],
  //       translations: {
  //         lo: "ຮາຍີ",
  //       },
  //     },
  //     {
  //       value: "ໂລໂລ",
  //       label: "Lolo",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ໂລໂລ"],
  //       translations: {
  //         lo: "ໂລໂລ",
  //       },
  //     },
  //     {
  //       value: "ຫໍ້",
  //       label: "Ho",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ຫໍ້"],
  //       translations: {
  //         lo: "ຫໍ້",
  //       },
  //     },
  //     {
  //       value: "ບຣູ",
  //       label: "Brou",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ບຣູ"],
  //       translations: {
  //         lo: "ບຣູ",
  //       },
  //     },
  //     {
  //       value: "ອື່ນໆ",
  //       label: "Others",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ອື່ນໆ"],
  //       translations: {
  //         lo: "ອື່ນໆ",
  //       },
  //     },
  //     {
  //       value: "ບໍ່ບອກ",
  //       label: "Not applicable",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["ບໍ່ບອກ"],
  //       translations: {
  //         lo: "ບໍ່ບອກ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ຊົນເຜົ່າ",
  //     en: "Ethnicity",
  //   },
  //   compulsory: true,
  // },
  // // newFamilyBookNumber
  // {
  //   code: "newFamilyBookNum",
  //   name: "New Family Book Number",
  //   id: "W4aInCTn8p5",
  //   disable: false,
  //   valueType: "TEXT",
  //   // pattern: /^[a-zA-Z\s]+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ເລກປະຈຳໂຕຢູ່ປຶືມສຳມະໂນຄົວ",
  //     en: "New Family Book Number",
  //   },
  //   compulsory: false,
  // },
  // // covid number
  // {
  //   code: "covidNum",
  //   name: "Covid Number",
  //   id: "rSETgSvyVpJ",
  //   disable: false,
  //   valueType: "TEXT",
  //   // pattern: /^[a-zA-Z\s]+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ເລກບັດຮັບວັກຊີນໂຄວິດ",
  //     en: "Covid Number",
  //   },
  //   compulsory: false,
  // },
  // // police number
  // {
  //   code: "policeNum",
  //   name: "Police Number",
  //   id: "PYgXM3R2TQd",
  //   disable: false,
  //   valueType: "MASK",
  //   pattern: /^\d+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ເລກບັດປະຈຳໂຕ",
  //     en: "Police Number",
  //   },
  //   compulsory: false,
  // },
  // // phone number
  // {
  //   code: "phoneNum",
  //   name: "Phone Number",
  //   id: "g9wNk1T3MLE",
  //   disable: false,
  //   valueType: "MASK",
  //   pattern: /^[0-9]+$/,
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ເບີໂທຕິດຕໍ່",
  //     en: "Phone Number",
  //   },
  //   compulsory: false,
  // },
  // {
  //   code: "nationality",
  //   name: "Nationality",
  //   id: "SpuwXA7NHUG",
  //   disable: false,
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "lao",
  //       label: "Lao",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Lao"],
  //       translations: {
  //         lo: "ລາວ",
  //       },
  //     },
  //     {
  //       value: "others",
  //       label: "Other Nationality",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Other Nationality"],
  //       translations: {
  //         lo: "ສັນຊາດອື່ນໆ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ສັນຊາດ",
  //     en: "Nationality",
  //   },
  //   formatter: (cellContent, row, rowIndex, extraData) => {
  //     return rowIndex + 1;
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "education",
  //   name: "Highest Education",
  //   id: "amhDvtb0SpN",
  //   disable: false,
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "primary-school",
  //       label: "Primary school",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Primary school"],
  //       translations: {
  //         lo: "ປະຖົມ",
  //       },
  //     },
  //     {
  //       value: "secondary-school",
  //       label: "Secondary School",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Secondary School"],
  //       translations: {
  //         lo: "ມັດທະຍົມຕົ້ນ",
  //       },
  //     },
  //     {
  //       value: "high-school",
  //       label: "High School",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["High School"],
  //       translations: {
  //         lo: "ມັດທະຍົມປາຍ",
  //       },
  //     },
  //     {
  //       value: "vocational",
  //       label: "Vocational or higher",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Vocational or higher"],
  //       translations: {
  //         lo: "ວິຊາຊີບຊັ້ນກາງ ຫຼື ຊັ້ນສູງ",
  //       },
  //     },
  //     {
  //       value: "bachelor",
  //       label: "Bachelor degree",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Bachelor degree"],
  //       translations: {
  //         lo: "ປະລິນຍາຕີ",
  //       },
  //     },
  //     {
  //       value: "bachelor-high",
  //       label: "Higher bachelor degree",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Higher bachelor degree"],
  //       translations: {
  //         lo: "ເໜືອປະລິນຍາຕີ",
  //       },
  //     },
  //     {
  //       value: "none",
  //       label: "None",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["None Education"],
  //       translations: {
  //         lo: "ບໍ່ມີການສຶກສາ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ລະດັບການສຶກສາ",
  //     en: "Highest Education",
  //   },
  // },
  // {
  //   code: "insurance",
  //   name: "Type of Insurance scheme",
  //   id: "btOLqyQrrXf",
  //   disable: false,
  //   valueType: "TEXT",
  //   compulsory: true,
  //   valueSet: [
  //     {
  //       value: "a1",
  //       label: "SASS",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["SASS"],
  //       translations: {
  //         lo: "ປະກັນສັງຄົມພາກລັດຖະກອນ (ອປລ)",
  //       },
  //     },
  //     {
  //       value: "a2",
  //       label: "SSO",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["SSO"],
  //       translations: {
  //         lo: "ປະກັນສັງຄົມພາກເອກະຊົນ (ອປສ)",
  //       },
  //     },
  //     {
  //       value: "b",
  //       label: "Military/Police Scheme",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Military/Police Scheme"],
  //       translations: {
  //         lo: "ປະກັນສັງຄົມຂອງທະຫານ (ພາກ ກປຊ)/ປະກັນສັງຄົມຂອງທະຫານ (ພາກ ກປສ)",
  //       },
  //     },
  //     {
  //       value: "c",
  //       label: "National Health Insurance",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["National Health Insurance"],
  //       translations: {
  //         lo: "ປະກັນສຸຂະພາບແຫ່ງຊາດ/NHI (ກປຊ)",
  //       },
  //     },
  //     {
  //       value: "d",
  //       label: "Community-based Health Insurance",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Community-based Health Insurance"],
  //       translations: {
  //         lo: "ກອງທຶນປະກັນສຸຂະພາບຊຸມຊົນ (ຄປສຊ)",
  //       },
  //     },
  //     // {
  //     //   value: "e",
  //     //   label: "Private Health Insurance",
  //     //   isDisabled: false,
  //     //   unique: false,
  //     //   multiple: ["Private Health Insurance"],
  //     //   translations: {
  //     //     lo: "ປະກັນສຸຂະພາບເອກະຊົນ",
  //     //   },
  //     // },
  //     {
  //       value: "g",
  //       label: "Dont Know",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Dont Know"],
  //       translations: {
  //         lo: "ບໍ່ຮູ້",
  //       },
  //     },
  //     {
  //       value: "f",
  //       label: "Dont have",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Dont have"],
  //       translations: {
  //         lo: "ບໍ່ໄດ້ເຂົ້າປະກັນສຸຂະພາບ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ປະເພດປະກັນສຸຂະພາບ",
  //     en: "Type of Insurance scheme",
  //   },
  // },
  // {
  //   code: "maritalstatus",
  //   name: "Marital status",
  //   id: "xXybyxfggiE",
  //   disable: false,
  //   valueType: "TEXT",
  //   valueSet: [
  //     {
  //       value: "S",
  //       label: "Never marry",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Never marry"],
  //       translations: {
  //         lo: "ບໍ່ເຄີຍແຕ່ງດອງ",
  //       },
  //     },
  //     {
  //       value: "M",
  //       label: "Marriage",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Marriage"],
  //       translations: {
  //         lo: "ແຕ່ງດອງ",
  //       },
  //     },
  //     {
  //       value: "D",
  //       label: "Divorce",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Divorce"],
  //       translations: {
  //         lo: "ຢ່າຮ້າງ",
  //       },
  //     },
  //     {
  //       value: "SE",
  //       label: "Separated",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Separated"],
  //       translations: {
  //         lo: "ແຍກກັນຢູ່",
  //       },
  //     },
  //     {
  //       value: "W",
  //       label: "Widow",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Widow"],
  //       translations: {
  //         lo: "ໝ້າຍ",
  //       },
  //     },
  //     {
  //       value: "C",
  //       label: "Cohabit",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Cohabit"],
  //       translations: {
  //         lo: "ຢູ່ຮ່ວມກັນ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ສະພາບສົມລົດ",
  //     en: "Marital status",
  //   },
  //   compulsory: true,
  // },
  // {
  //   code: "agetype",
  //   name: "Type of Age",
  //   id: "Mn6DGipd0yD",
  //   disable: false,
  //   hidden: false,
  //   hiddenCol: true,
  //   valueType: "TEXT",
  //   compulsory: true,
  //   valueSet: [
  //     {
  //       value: "DOB",
  //       label: "Date of birth",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Date of birth"],
  //       translations: {
  //         lo: "ວັນເດືອນປີເກີດ",
  //       },
  //     },
  //     {
  //       value: "birthyear",
  //       label: "Birth Year",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Birth Year"],
  //       translations: {
  //         lo: "ປີເກີດ",
  //       },
  //     },
  //     /**
  //      * Temp turn off to avoid user enter this data, it hard to auto age increment
  //      *  */
  //     // {
  //     //   value: "age",
  //     //   label: "Age in years",
  //     //   isDisabled: false,
  //     //   unique: false,
  //     //   multiple: ["Age in years"],
  //     //   translations: {
  //     //     lo: "ອາຍຸ(ປີ)",
  //     //   },
  //     // },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ອາຍຸ(ປີ)",
  //     en: "Type of Age",
  //   },
  // },
  // {
  //   code: "DOB",
  //   name: "Date of birth",
  //   id: "fqy4x9rbdGi",
  //   disable: false,
  //   hidden: true,
  //   hiddenCol: true,
  //   valueType: "DATE",
  //   sort: null,
  //   translations: {
  //     lo: "ວັນເດືອນປີເກີດ",
  //     en: "Date of birth",
  //   },
  // },
  // {
  //   code: "birthyear",
  //   name: "Birth Year",
  //   id: "J9UdB29DZnl",
  //   disable: false,
  //   hidden: true,
  //   hiddenCol: true,
  //   valueType: "DATE",
  //   periodType: "year", //https://material-ui-pickers.dev/api/KeyboardDatePicker
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ປີເກີດ",
  //     en: "Birth Year",
  //   },
  // },
  // {
  //   code: "age",
  //   name: "Age in years",
  //   id: "Mn6DGipd0yE",
  //   disable: false,
  //   hiddenCol: true,
  //   hidden: true,
  //   valueType: "NUMBER",
  //   attribute: {
  //     maxLength: 3,
  //     max: 120,
  //   },
  //   valueSet: null,
  //   sort: null,
  //   translations: {
  //     lo: "ອາຍຸ(ປີ)",
  //     en: "Age in years",
  //   },
  // },
  // // {
  // //   code: "age",
  // //   name: "Age",
  // //   id: "age",
  // //   valueType: "TEXT",
  // //   additionCol: true,
  // //   valueSet: null,
  // //   hiddenCol: true,
  // //   sort: null,
  // //   translations: {
  // //     lo: "ອາຍຸ",
  // //     en: "Age",
  // //   },
  // // },
  // {
  //   code: "status",
  //   name: "Status",
  //   id: "K9UdB29DZnl",
  //   disable: false,
  //   hidden: false,
  //   valueType: "TEXT",
  //   defaultValue: "Active",
  //   valueSet: [
  //     {
  //       value: "active",
  //       label: "Active",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Active"],
  //       translations: {
  //         lo: "ມີໜ້າໃນຄອບຄົວ",
  //       },
  //     },
  //     {
  //       value: "transfer-out",
  //       label: "Transferred",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Transferred"],
  //       translations: {
  //         lo: "ຍ້າຍອອກ",
  //       },
  //     },
  //     {
  //       value: "dead",
  //       label: "Dead",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Dead"],
  //       translations: {
  //         lo: "ເສຍຊີວິດ",
  //       },
  //     },
  //     {
  //       value: "not-residing",
  //       label: "Not residing",
  //       isDisabled: false,
  //       unique: false,
  //       multiple: ["Not residing"],
  //       translations: {
  //         lo: "ຢູ່ນອກປະເທດ",
  //       },
  //     },
  //   ],
  //   sort: null,
  //   translations: {
  //     lo: "ສະຖານະ",
  //     en: "Status",
  //   },
  // },
];

export default originMetadata;
